# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' AuthModelLocal Class
#'
#' @field username 
#' @field password 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AuthModelLocal <- R6::R6Class(
  'AuthModelLocal',
  public = list(
    `username` = NULL,
    `password` = NULL,
    initialize = function(`username`, `password`){
      if (!missing(`username`)) {
        stopifnot(is.character(`username`), length(`username`) == 1)
        self$`username` <- `username`
      }
      if (!missing(`password`)) {
        stopifnot(is.character(`password`), length(`password`) == 1)
        self$`password` <- `password`
      }
    },
    toJSON = function() {
      AuthModelLocalObject <- list()
      if (!is.null(self$`username`)) {
        AuthModelLocalObject[['username']] <- self$`username`
      }
      if (!is.null(self$`password`)) {
        AuthModelLocalObject[['password']] <- self$`password`
      }

      AuthModelLocalObject
    },
    fromJSON = function(AuthModelLocalJson) {
      AuthModelLocalObject <- jsonlite::fromJSON(AuthModelLocalJson)
      if (!is.null(AuthModelLocalObject$`username`)) {
        self$`username` <- AuthModelLocalObject$`username`
      }
      if (!is.null(AuthModelLocalObject$`password`)) {
        self$`password` <- AuthModelLocalObject$`password`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "username": %s,
           "password": %s
        }',
        self$`username`,
        self$`password`
      )
    },
    fromJSONString = function(AuthModelLocalJson) {
      AuthModelLocalObject <- jsonlite::fromJSON(AuthModelLocalJson)
      self$`username` <- AuthModelLocalObject$`username`
      self$`password` <- AuthModelLocalObject$`password`
    }
  )
)
