# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' CertFileModel Class
#'
#' @field name 
#' @field body 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CertFileModel <- R6::R6Class(
  'CertFileModel',
  public = list(
    `name` = NULL,
    `body` = NULL,
    initialize = function(`name`, `body`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`body`)) {
        stopifnot(is.character(`body`), length(`body`) == 1)
        self$`body` <- `body`
      }
    },
    toJSON = function() {
      CertFileModelObject <- list()
      if (!is.null(self$`name`)) {
        CertFileModelObject[['name']] <- self$`name`
      }
      if (!is.null(self$`body`)) {
        CertFileModelObject[['body']] <- self$`body`
      }

      CertFileModelObject
    },
    fromJSON = function(CertFileModelJson) {
      CertFileModelObject <- jsonlite::fromJSON(CertFileModelJson)
      if (!is.null(CertFileModelObject$`name`)) {
        self$`name` <- CertFileModelObject$`name`
      }
      if (!is.null(CertFileModelObject$`body`)) {
        self$`body` <- CertFileModelObject$`body`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "body": %s
        }',
        self$`name`,
        self$`body`
      )
    },
    fromJSONString = function(CertFileModelJson) {
      CertFileModelObject <- jsonlite::fromJSON(CertFileModelJson)
      self$`name` <- CertFileModelObject$`name`
      self$`body` <- CertFileModelObject$`body`
    }
  )
)
