# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' CICDStatusModel Class
#'
#' @field state 
#' @field reason 
#' @field programPath 
#' @field repo 
#' @field commitID 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CICDStatusModel <- R6::R6Class(
  'CICDStatusModel',
  public = list(
    `state` = NULL,
    `reason` = NULL,
    `programPath` = NULL,
    `repo` = NULL,
    `commitID` = NULL,
    initialize = function(`state`, `reason`, `programPath`, `repo`, `commitID`){
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`reason`)) {
        stopifnot(is.character(`reason`), length(`reason`) == 1)
        self$`reason` <- `reason`
      }
      if (!missing(`programPath`)) {
        stopifnot(is.character(`programPath`), length(`programPath`) == 1)
        self$`programPath` <- `programPath`
      }
      if (!missing(`repo`)) {
        stopifnot(is.character(`repo`), length(`repo`) == 1)
        self$`repo` <- `repo`
      }
      if (!missing(`commitID`)) {
        stopifnot(is.character(`commitID`), length(`commitID`) == 1)
        self$`commitID` <- `commitID`
      }
    },
    toJSON = function() {
      CICDStatusModelObject <- list()
      if (!is.null(self$`state`)) {
        CICDStatusModelObject[['state']] <- self$`state`
      }
      if (!is.null(self$`reason`)) {
        CICDStatusModelObject[['reason']] <- self$`reason`
      }
      if (!is.null(self$`programPath`)) {
        CICDStatusModelObject[['programPath']] <- self$`programPath`
      }
      if (!is.null(self$`repo`)) {
        CICDStatusModelObject[['repo']] <- self$`repo`
      }
      if (!is.null(self$`commitID`)) {
        CICDStatusModelObject[['commitID']] <- self$`commitID`
      }

      CICDStatusModelObject
    },
    fromJSON = function(CICDStatusModelJson) {
      CICDStatusModelObject <- jsonlite::fromJSON(CICDStatusModelJson)
      if (!is.null(CICDStatusModelObject$`state`)) {
        self$`state` <- CICDStatusModelObject$`state`
      }
      if (!is.null(CICDStatusModelObject$`reason`)) {
        self$`reason` <- CICDStatusModelObject$`reason`
      }
      if (!is.null(CICDStatusModelObject$`programPath`)) {
        self$`programPath` <- CICDStatusModelObject$`programPath`
      }
      if (!is.null(CICDStatusModelObject$`repo`)) {
        self$`repo` <- CICDStatusModelObject$`repo`
      }
      if (!is.null(CICDStatusModelObject$`commitID`)) {
        self$`commitID` <- CICDStatusModelObject$`commitID`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "state": %s,
           "reason": %s,
           "programPath": %s,
           "repo": %s,
           "commitID": %s
        }',
        self$`state`,
        self$`reason`,
        self$`programPath`,
        self$`repo`,
        self$`commitID`
      )
    },
    fromJSONString = function(CICDStatusModelJson) {
      CICDStatusModelObject <- jsonlite::fromJSON(CICDStatusModelJson)
      self$`state` <- CICDStatusModelObject$`state`
      self$`reason` <- CICDStatusModelObject$`reason`
      self$`programPath` <- CICDStatusModelObject$`programPath`
      self$`repo` <- CICDStatusModelObject$`repo`
      self$`commitID` <- CICDStatusModelObject$`commitID`
    }
  )
)
