# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ConfigFileModel Class
#'
#' @field name 
#' @field body 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ConfigFileModel <- R6::R6Class(
  'ConfigFileModel',
  public = list(
    `name` = NULL,
    `body` = NULL,
    initialize = function(`name`, `body`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`body`)) {
        stopifnot(is.character(`body`), length(`body`) == 1)
        self$`body` <- `body`
      }
    },
    toJSON = function() {
      ConfigFileModelObject <- list()
      if (!is.null(self$`name`)) {
        ConfigFileModelObject[['name']] <- self$`name`
      }
      if (!is.null(self$`body`)) {
        ConfigFileModelObject[['body']] <- self$`body`
      }

      ConfigFileModelObject
    },
    fromJSON = function(ConfigFileModelJson) {
      ConfigFileModelObject <- jsonlite::fromJSON(ConfigFileModelJson)
      if (!is.null(ConfigFileModelObject$`name`)) {
        self$`name` <- ConfigFileModelObject$`name`
      }
      if (!is.null(ConfigFileModelObject$`body`)) {
        self$`body` <- ConfigFileModelObject$`body`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "body": %s
        }',
        self$`name`,
        self$`body`
      )
    },
    fromJSONString = function(ConfigFileModelJson) {
      ConfigFileModelObject <- jsonlite::fromJSON(ConfigFileModelJson)
      self$`name` <- ConfigFileModelObject$`name`
      self$`body` <- ConfigFileModelObject$`body`
    }
  )
)
