# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' CpuModel Class
#'
#' @field version 
#' @field cpus 
#' @field architecture 
#' @field cpu_op_models 
#' @field byte_order 
#' @field threads_per_core 
#' @field cores_per_socket 
#' @field sockets 
#' @field vendor 
#' @field modelNumber 
#' @field cores 
#' @field modelName 
#' @field frequency 
#' @field frequency_max 
#' @field frequency_min 
#' @field virtualization 
#' @field family 
#' @field l1d_cache 
#' @field l1i_cache 
#' @field l2_cache 
#' @field l3_cache 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CpuModel <- R6::R6Class(
  'CpuModel',
  public = list(
    `version` = NULL,
    `cpus` = NULL,
    `architecture` = NULL,
    `cpu_op_models` = NULL,
    `byte_order` = NULL,
    `threads_per_core` = NULL,
    `cores_per_socket` = NULL,
    `sockets` = NULL,
    `vendor` = NULL,
    `modelNumber` = NULL,
    `cores` = NULL,
    `modelName` = NULL,
    `frequency` = NULL,
    `frequency_max` = NULL,
    `frequency_min` = NULL,
    `virtualization` = NULL,
    `family` = NULL,
    `l1d_cache` = NULL,
    `l1i_cache` = NULL,
    `l2_cache` = NULL,
    `l3_cache` = NULL,
    initialize = function(`version`, `cpus`, `architecture`, `cpu_op_models`, `byte_order`, `threads_per_core`, `cores_per_socket`, `sockets`, `vendor`, `modelNumber`, `cores`, `modelName`, `frequency`, `frequency_max`, `frequency_min`, `virtualization`, `family`, `l1d_cache`, `l1i_cache`, `l2_cache`, `l3_cache`){
      if (!missing(`version`)) {
        stopifnot(is.character(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
      if (!missing(`cpus`)) {
        stopifnot(is.character(`cpus`), length(`cpus`) == 1)
        self$`cpus` <- `cpus`
      }
      if (!missing(`architecture`)) {
        stopifnot(is.character(`architecture`), length(`architecture`) == 1)
        self$`architecture` <- `architecture`
      }
      if (!missing(`cpu_op_models`)) {
        stopifnot(is.character(`cpu_op_models`), length(`cpu_op_models`) == 1)
        self$`cpu_op_models` <- `cpu_op_models`
      }
      if (!missing(`byte_order`)) {
        stopifnot(is.character(`byte_order`), length(`byte_order`) == 1)
        self$`byte_order` <- `byte_order`
      }
      if (!missing(`threads_per_core`)) {
        stopifnot(is.numeric(`threads_per_core`), length(`threads_per_core`) == 1)
        self$`threads_per_core` <- `threads_per_core`
      }
      if (!missing(`cores_per_socket`)) {
        stopifnot(is.numeric(`cores_per_socket`), length(`cores_per_socket`) == 1)
        self$`cores_per_socket` <- `cores_per_socket`
      }
      if (!missing(`sockets`)) {
        stopifnot(is.numeric(`sockets`), length(`sockets`) == 1)
        self$`sockets` <- `sockets`
      }
      if (!missing(`vendor`)) {
        stopifnot(is.character(`vendor`), length(`vendor`) == 1)
        self$`vendor` <- `vendor`
      }
      if (!missing(`modelNumber`)) {
        stopifnot(is.character(`modelNumber`), length(`modelNumber`) == 1)
        self$`modelNumber` <- `modelNumber`
      }
      if (!missing(`cores`)) {
        stopifnot(is.numeric(`cores`), length(`cores`) == 1)
        self$`cores` <- `cores`
      }
      if (!missing(`modelName`)) {
        stopifnot(is.character(`modelName`), length(`modelName`) == 1)
        self$`modelName` <- `modelName`
      }
      if (!missing(`frequency`)) {
        stopifnot(is.character(`frequency`), length(`frequency`) == 1)
        self$`frequency` <- `frequency`
      }
      if (!missing(`frequency_max`)) {
        stopifnot(is.character(`frequency_max`), length(`frequency_max`) == 1)
        self$`frequency_max` <- `frequency_max`
      }
      if (!missing(`frequency_min`)) {
        stopifnot(is.character(`frequency_min`), length(`frequency_min`) == 1)
        self$`frequency_min` <- `frequency_min`
      }
      if (!missing(`virtualization`)) {
        stopifnot(is.character(`virtualization`), length(`virtualization`) == 1)
        self$`virtualization` <- `virtualization`
      }
      if (!missing(`family`)) {
        stopifnot(is.character(`family`), length(`family`) == 1)
        self$`family` <- `family`
      }
      if (!missing(`l1d_cache`)) {
        stopifnot(is.character(`l1d_cache`), length(`l1d_cache`) == 1)
        self$`l1d_cache` <- `l1d_cache`
      }
      if (!missing(`l1i_cache`)) {
        stopifnot(is.character(`l1i_cache`), length(`l1i_cache`) == 1)
        self$`l1i_cache` <- `l1i_cache`
      }
      if (!missing(`l2_cache`)) {
        stopifnot(is.character(`l2_cache`), length(`l2_cache`) == 1)
        self$`l2_cache` <- `l2_cache`
      }
      if (!missing(`l3_cache`)) {
        stopifnot(is.character(`l3_cache`), length(`l3_cache`) == 1)
        self$`l3_cache` <- `l3_cache`
      }
    },
    toJSON = function() {
      CpuModelObject <- list()
      if (!is.null(self$`version`)) {
        CpuModelObject[['version']] <- self$`version`
      }
      if (!is.null(self$`cpus`)) {
        CpuModelObject[['cpus']] <- self$`cpus`
      }
      if (!is.null(self$`architecture`)) {
        CpuModelObject[['architecture']] <- self$`architecture`
      }
      if (!is.null(self$`cpu_op_models`)) {
        CpuModelObject[['cpu_op_models']] <- self$`cpu_op_models`
      }
      if (!is.null(self$`byte_order`)) {
        CpuModelObject[['byte_order']] <- self$`byte_order`
      }
      if (!is.null(self$`threads_per_core`)) {
        CpuModelObject[['threads_per_core']] <- self$`threads_per_core`
      }
      if (!is.null(self$`cores_per_socket`)) {
        CpuModelObject[['cores_per_socket']] <- self$`cores_per_socket`
      }
      if (!is.null(self$`sockets`)) {
        CpuModelObject[['sockets']] <- self$`sockets`
      }
      if (!is.null(self$`vendor`)) {
        CpuModelObject[['vendor']] <- self$`vendor`
      }
      if (!is.null(self$`modelNumber`)) {
        CpuModelObject[['modelNumber']] <- self$`modelNumber`
      }
      if (!is.null(self$`cores`)) {
        CpuModelObject[['cores']] <- self$`cores`
      }
      if (!is.null(self$`modelName`)) {
        CpuModelObject[['modelName']] <- self$`modelName`
      }
      if (!is.null(self$`frequency`)) {
        CpuModelObject[['frequency']] <- self$`frequency`
      }
      if (!is.null(self$`frequency_max`)) {
        CpuModelObject[['frequency_max']] <- self$`frequency_max`
      }
      if (!is.null(self$`frequency_min`)) {
        CpuModelObject[['frequency_min']] <- self$`frequency_min`
      }
      if (!is.null(self$`virtualization`)) {
        CpuModelObject[['virtualization']] <- self$`virtualization`
      }
      if (!is.null(self$`family`)) {
        CpuModelObject[['family']] <- self$`family`
      }
      if (!is.null(self$`l1d_cache`)) {
        CpuModelObject[['l1d_cache']] <- self$`l1d_cache`
      }
      if (!is.null(self$`l1i_cache`)) {
        CpuModelObject[['l1i_cache']] <- self$`l1i_cache`
      }
      if (!is.null(self$`l2_cache`)) {
        CpuModelObject[['l2_cache']] <- self$`l2_cache`
      }
      if (!is.null(self$`l3_cache`)) {
        CpuModelObject[['l3_cache']] <- self$`l3_cache`
      }

      CpuModelObject
    },
    fromJSON = function(CpuModelJson) {
      CpuModelObject <- jsonlite::fromJSON(CpuModelJson)
      if (!is.null(CpuModelObject$`version`)) {
        self$`version` <- CpuModelObject$`version`
      }
      if (!is.null(CpuModelObject$`cpus`)) {
        self$`cpus` <- CpuModelObject$`cpus`
      }
      if (!is.null(CpuModelObject$`architecture`)) {
        self$`architecture` <- CpuModelObject$`architecture`
      }
      if (!is.null(CpuModelObject$`cpu_op_models`)) {
        self$`cpu_op_models` <- CpuModelObject$`cpu_op_models`
      }
      if (!is.null(CpuModelObject$`byte_order`)) {
        self$`byte_order` <- CpuModelObject$`byte_order`
      }
      if (!is.null(CpuModelObject$`threads_per_core`)) {
        self$`threads_per_core` <- CpuModelObject$`threads_per_core`
      }
      if (!is.null(CpuModelObject$`cores_per_socket`)) {
        self$`cores_per_socket` <- CpuModelObject$`cores_per_socket`
      }
      if (!is.null(CpuModelObject$`sockets`)) {
        self$`sockets` <- CpuModelObject$`sockets`
      }
      if (!is.null(CpuModelObject$`vendor`)) {
        self$`vendor` <- CpuModelObject$`vendor`
      }
      if (!is.null(CpuModelObject$`modelNumber`)) {
        self$`modelNumber` <- CpuModelObject$`modelNumber`
      }
      if (!is.null(CpuModelObject$`cores`)) {
        self$`cores` <- CpuModelObject$`cores`
      }
      if (!is.null(CpuModelObject$`modelName`)) {
        self$`modelName` <- CpuModelObject$`modelName`
      }
      if (!is.null(CpuModelObject$`frequency`)) {
        self$`frequency` <- CpuModelObject$`frequency`
      }
      if (!is.null(CpuModelObject$`frequency_max`)) {
        self$`frequency_max` <- CpuModelObject$`frequency_max`
      }
      if (!is.null(CpuModelObject$`frequency_min`)) {
        self$`frequency_min` <- CpuModelObject$`frequency_min`
      }
      if (!is.null(CpuModelObject$`virtualization`)) {
        self$`virtualization` <- CpuModelObject$`virtualization`
      }
      if (!is.null(CpuModelObject$`family`)) {
        self$`family` <- CpuModelObject$`family`
      }
      if (!is.null(CpuModelObject$`l1d_cache`)) {
        self$`l1d_cache` <- CpuModelObject$`l1d_cache`
      }
      if (!is.null(CpuModelObject$`l1i_cache`)) {
        self$`l1i_cache` <- CpuModelObject$`l1i_cache`
      }
      if (!is.null(CpuModelObject$`l2_cache`)) {
        self$`l2_cache` <- CpuModelObject$`l2_cache`
      }
      if (!is.null(CpuModelObject$`l3_cache`)) {
        self$`l3_cache` <- CpuModelObject$`l3_cache`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "version": %s,
           "cpus": %s,
           "architecture": %s,
           "cpu_op_models": %s,
           "byte_order": %s,
           "threads_per_core": %d,
           "cores_per_socket": %d,
           "sockets": %d,
           "vendor": %s,
           "modelNumber": %s,
           "cores": %d,
           "modelName": %s,
           "frequency": %s,
           "frequency_max": %s,
           "frequency_min": %s,
           "virtualization": %s,
           "family": %s,
           "l1d_cache": %s,
           "l1i_cache": %s,
           "l2_cache": %s,
           "l3_cache": %s
        }',
        self$`version`,
        self$`cpus`,
        self$`architecture`,
        self$`cpu_op_models`,
        self$`byte_order`,
        self$`threads_per_core`,
        self$`cores_per_socket`,
        self$`sockets`,
        self$`vendor`,
        self$`modelNumber`,
        self$`cores`,
        self$`modelName`,
        self$`frequency`,
        self$`frequency_max`,
        self$`frequency_min`,
        self$`virtualization`,
        self$`family`,
        self$`l1d_cache`,
        self$`l1i_cache`,
        self$`l2_cache`,
        self$`l3_cache`
      )
    },
    fromJSONString = function(CpuModelJson) {
      CpuModelObject <- jsonlite::fromJSON(CpuModelJson)
      self$`version` <- CpuModelObject$`version`
      self$`cpus` <- CpuModelObject$`cpus`
      self$`architecture` <- CpuModelObject$`architecture`
      self$`cpu_op_models` <- CpuModelObject$`cpu_op_models`
      self$`byte_order` <- CpuModelObject$`byte_order`
      self$`threads_per_core` <- CpuModelObject$`threads_per_core`
      self$`cores_per_socket` <- CpuModelObject$`cores_per_socket`
      self$`sockets` <- CpuModelObject$`sockets`
      self$`vendor` <- CpuModelObject$`vendor`
      self$`modelNumber` <- CpuModelObject$`modelNumber`
      self$`cores` <- CpuModelObject$`cores`
      self$`modelName` <- CpuModelObject$`modelName`
      self$`frequency` <- CpuModelObject$`frequency`
      self$`frequency_max` <- CpuModelObject$`frequency_max`
      self$`frequency_min` <- CpuModelObject$`frequency_min`
      self$`virtualization` <- CpuModelObject$`virtualization`
      self$`family` <- CpuModelObject$`family`
      self$`l1d_cache` <- CpuModelObject$`l1d_cache`
      self$`l1i_cache` <- CpuModelObject$`l1i_cache`
      self$`l2_cache` <- CpuModelObject$`l2_cache`
      self$`l3_cache` <- CpuModelObject$`l3_cache`
    }
  )
)
