# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' CustomKVModel Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CustomKVModel <- R6::R6Class(
  'CustomKVModel',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      CustomKVModelObject <- list()

      CustomKVModelObject
    },
    fromJSON = function(CustomKVModelJson) {
      CustomKVModelObject <- jsonlite::fromJSON(CustomKVModelJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(CustomKVModelJson) {
      CustomKVModelObject <- jsonlite::fromJSON(CustomKVModelJson)
    }
  )
)
