# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' CustomContainerModelImage Class
#'
#' @field path 
#' @field username 
#' @field password 
#' @field runas 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CustomContainerModelImage <- R6::R6Class(
  'CustomContainerModelImage',
  public = list(
    `path` = NULL,
    `username` = NULL,
    `password` = NULL,
    `runas` = NULL,
    initialize = function(`path`, `username`, `password`, `runas`){
      if (!missing(`path`)) {
        stopifnot(is.character(`path`), length(`path`) == 1)
        self$`path` <- `path`
      }
      if (!missing(`username`)) {
        stopifnot(is.character(`username`), length(`username`) == 1)
        self$`username` <- `username`
      }
      if (!missing(`password`)) {
        stopifnot(is.character(`password`), length(`password`) == 1)
        self$`password` <- `password`
      }
      if (!missing(`runas`)) {
        stopifnot(is.character(`runas`), length(`runas`) == 1)
        self$`runas` <- `runas`
      }
    },
    toJSON = function() {
      CustomContainerModelImageObject <- list()
      if (!is.null(self$`path`)) {
        CustomContainerModelImageObject[['path']] <- self$`path`
      }
      if (!is.null(self$`username`)) {
        CustomContainerModelImageObject[['username']] <- self$`username`
      }
      if (!is.null(self$`password`)) {
        CustomContainerModelImageObject[['password']] <- self$`password`
      }
      if (!is.null(self$`runas`)) {
        CustomContainerModelImageObject[['runas']] <- self$`runas`
      }

      CustomContainerModelImageObject
    },
    fromJSON = function(CustomContainerModelImageJson) {
      CustomContainerModelImageObject <- jsonlite::fromJSON(CustomContainerModelImageJson)
      if (!is.null(CustomContainerModelImageObject$`path`)) {
        self$`path` <- CustomContainerModelImageObject$`path`
      }
      if (!is.null(CustomContainerModelImageObject$`username`)) {
        self$`username` <- CustomContainerModelImageObject$`username`
      }
      if (!is.null(CustomContainerModelImageObject$`password`)) {
        self$`password` <- CustomContainerModelImageObject$`password`
      }
      if (!is.null(CustomContainerModelImageObject$`runas`)) {
        self$`runas` <- CustomContainerModelImageObject$`runas`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "path": %s,
           "username": %s,
           "password": %s,
           "runas": %s
        }',
        self$`path`,
        self$`username`,
        self$`password`,
        self$`runas`
      )
    },
    fromJSONString = function(CustomContainerModelImageJson) {
      CustomContainerModelImageObject <- jsonlite::fromJSON(CustomContainerModelImageJson)
      self$`path` <- CustomContainerModelImageObject$`path`
      self$`username` <- CustomContainerModelImageObject$`username`
      self$`password` <- CustomContainerModelImageObject$`password`
      self$`runas` <- CustomContainerModelImageObject$`runas`
    }
  )
)
