# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Data37 Class
#'
#' @field featuresets 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Data37 <- R6::R6Class(
  'Data37',
  public = list(
    `featuresets` = NULL,
    initialize = function(`featuresets`){
      if (!missing(`featuresets`)) {
        stopifnot(is.list(`featuresets`), length(`featuresets`) != 0)
        lapply(`featuresets`, function(x) stopifnot(is.character(x)))
        self$`featuresets` <- `featuresets`
      }
    },
    toJSON = function() {
      Data37Object <- list()
      if (!is.null(self$`featuresets`)) {
        Data37Object[['featuresets']] <- self$`featuresets`
      }

      Data37Object
    },
    fromJSON = function(Data37Json) {
      Data37Object <- jsonlite::fromJSON(Data37Json)
      if (!is.null(Data37Object$`featuresets`)) {
        self$`featuresets` <- Data37Object$`featuresets`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "featuresets": [%s]
        }',
        lapply(self$`featuresets`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(Data37Json) {
      Data37Object <- jsonlite::fromJSON(Data37Json)
      self$`featuresets` <- Data37Object$`featuresets`
    }
  )
)
