# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Data5 Class
#'
#' @field users 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Data5 <- R6::R6Class(
  'Data5',
  public = list(
    `users` = NULL,
    initialize = function(`users`){
      if (!missing(`users`)) {
        stopifnot(is.list(`users`), length(`users`) != 0)
        lapply(`users`, function(x) stopifnot(is.character(x)))
        self$`users` <- `users`
      }
    },
    toJSON = function() {
      Data5Object <- list()
      if (!is.null(self$`users`)) {
        Data5Object[['users']] <- self$`users`
      }

      Data5Object
    },
    fromJSON = function(Data5Json) {
      Data5Object <- jsonlite::fromJSON(Data5Json)
      if (!is.null(Data5Object$`users`)) {
        self$`users` <- Data5Object$`users`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "users": [%s]
        }',
        lapply(self$`users`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(Data5Json) {
      Data5Object <- jsonlite::fromJSON(Data5Json)
      self$`users` <- Data5Object$`users`
    }
  )
)
