# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Data25 Class
#'
#' @field pools 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Data25 <- R6::R6Class(
  'Data25',
  public = list(
    `pools` = NULL,
    initialize = function(`pools`){
      if (!missing(`pools`)) {
        stopifnot(is.list(`pools`), length(`pools`) != 0)
        lapply(`pools`, function(x) stopifnot(is.character(x)))
        self$`pools` <- `pools`
      }
    },
    toJSON = function() {
      Data25Object <- list()
      if (!is.null(self$`pools`)) {
        Data25Object[['pools']] <- self$`pools`
      }

      Data25Object
    },
    fromJSON = function(Data25Json) {
      Data25Object <- jsonlite::fromJSON(Data25Json)
      if (!is.null(Data25Object$`pools`)) {
        self$`pools` <- Data25Object$`pools`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "pools": [%s]
        }',
        lapply(self$`pools`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(Data25Json) {
      Data25Object <- jsonlite::fromJSON(Data25Json)
      self$`pools` <- Data25Object$`pools`
    }
  )
)
