# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Data8 Class
#'
#' @field description 
#' @field tags 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Data8 <- R6::R6Class(
  'Data8',
  public = list(
    `description` = NULL,
    `tags` = NULL,
    initialize = function(`description`, `tags`){
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`tags`)) {
        stopifnot(is.list(`tags`), length(`tags`) != 0)
        lapply(`tags`, function(x) stopifnot(is.character(x)))
        self$`tags` <- `tags`
      }
    },
    toJSON = function() {
      Data8Object <- list()
      if (!is.null(self$`description`)) {
        Data8Object[['description']] <- self$`description`
      }
      if (!is.null(self$`tags`)) {
        Data8Object[['tags']] <- self$`tags`
      }

      Data8Object
    },
    fromJSON = function(Data8Json) {
      Data8Object <- jsonlite::fromJSON(Data8Json)
      if (!is.null(Data8Object$`description`)) {
        self$`description` <- Data8Object$`description`
      }
      if (!is.null(Data8Object$`tags`)) {
        self$`tags` <- Data8Object$`tags`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "description": %s,
           "tags": [%s]
        }',
        self$`description`,
        lapply(self$`tags`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(Data8Json) {
      Data8Object <- jsonlite::fromJSON(Data8Json)
      self$`description` <- Data8Object$`description`
      self$`tags` <- Data8Object$`tags`
    }
  )
)
