# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Data15 Class
#'
#' @field name 
#' @field description 
#' @field serving 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Data15 <- R6::R6Class(
  'Data15',
  public = list(
    `name` = NULL,
    `description` = NULL,
    `serving` = NULL,
    initialize = function(`name`, `description`, `serving`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`serving`)) {
        stopifnot(R6::is.R6(`serving`))
        self$`serving` <- `serving`
      }
    },
    toJSON = function() {
      Data15Object <- list()
      if (!is.null(self$`name`)) {
        Data15Object[['name']] <- self$`name`
      }
      if (!is.null(self$`description`)) {
        Data15Object[['description']] <- self$`description`
      }
      if (!is.null(self$`serving`)) {
        Data15Object[['serving']] <- self$`serving`$toJSON()
      }

      Data15Object
    },
    fromJSON = function(Data15Json) {
      Data15Object <- jsonlite::fromJSON(Data15Json)
      if (!is.null(Data15Object$`name`)) {
        self$`name` <- Data15Object$`name`
      }
      if (!is.null(Data15Object$`description`)) {
        self$`description` <- Data15Object$`description`
      }
      if (!is.null(Data15Object$`serving`)) {
        servingObject <- InferenceJobModel$new()
        servingObject$fromJSON(jsonlite::toJSON(Data15Object$serving, auto_unbox = TRUE))
        self$`serving` <- servingObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "description": %s,
           "serving": %s
        }',
        self$`name`,
        self$`description`,
        self$`serving`$toJSON()
      )
    },
    fromJSONString = function(Data15Json) {
      Data15Object <- jsonlite::fromJSON(Data15Json)
      self$`name` <- Data15Object$`name`
      self$`description` <- Data15Object$`description`
      InferenceJobModelObject <- InferenceJobModel$new()
      self$`serving` <- InferenceJobModelObject$fromJSON(jsonlite::toJSON(Data15Object$serving, auto_unbox = TRUE))
    }
  )
)
