# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Data27 Class
#'
#' @field metrics Metrics
#' @field eval_run Eval Run
#' @field eval_run_name Eval Run Name
#' @field artifacts_url URL of artifacts in storage
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Data27 <- R6::R6Class(
  'Data27',
  public = list(
    `metrics` = NULL,
    `eval_run` = NULL,
    `eval_run_name` = NULL,
    `artifacts_url` = NULL,
    initialize = function(`metrics`, `eval_run`, `eval_run_name`, `artifacts_url`){
      if (!missing(`metrics`)) {
        stopifnot(R6::is.R6(`metrics`))
        self$`metrics` <- `metrics`
      }
      if (!missing(`eval_run`)) {
        stopifnot(is.character(`eval_run`), length(`eval_run`) == 1)
        self$`eval_run` <- `eval_run`
      }
      if (!missing(`eval_run_name`)) {
        stopifnot(is.character(`eval_run_name`), length(`eval_run_name`) == 1)
        self$`eval_run_name` <- `eval_run_name`
      }
      if (!missing(`artifacts_url`)) {
        stopifnot(is.character(`artifacts_url`), length(`artifacts_url`) == 1)
        self$`artifacts_url` <- `artifacts_url`
      }
    },
    toJSON = function() {
      Data27Object <- list()
      if (!is.null(self$`metrics`)) {
        Data27Object[['metrics']] <- self$`metrics`$toJSON()
      }
      if (!is.null(self$`eval_run`)) {
        Data27Object[['eval_run']] <- self$`eval_run`
      }
      if (!is.null(self$`eval_run_name`)) {
        Data27Object[['eval_run_name']] <- self$`eval_run_name`
      }
      if (!is.null(self$`artifacts_url`)) {
        Data27Object[['artifacts_url']] <- self$`artifacts_url`
      }

      Data27Object
    },
    fromJSON = function(Data27Json) {
      Data27Object <- jsonlite::fromJSON(Data27Json)
      if (!is.null(Data27Object$`metrics`)) {
        metricsObject <- TODO_OBJECT_MAPPING$new()
        metricsObject$fromJSON(jsonlite::toJSON(Data27Object$metrics, auto_unbox = TRUE))
        self$`metrics` <- metricsObject
      }
      if (!is.null(Data27Object$`eval_run`)) {
        self$`eval_run` <- Data27Object$`eval_run`
      }
      if (!is.null(Data27Object$`eval_run_name`)) {
        self$`eval_run_name` <- Data27Object$`eval_run_name`
      }
      if (!is.null(Data27Object$`artifacts_url`)) {
        self$`artifacts_url` <- Data27Object$`artifacts_url`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "metrics": %s,
           "eval_run": %s,
           "eval_run_name": %s,
           "artifacts_url": %s
        }',
        self$`metrics`$toJSON(),
        self$`eval_run`,
        self$`eval_run_name`,
        self$`artifacts_url`
      )
    },
    fromJSONString = function(Data27Json) {
      Data27Object <- jsonlite::fromJSON(Data27Json)
      TODO_OBJECT_MAPPINGObject <- TODO_OBJECT_MAPPING$new()
      self$`metrics` <- TODO_OBJECT_MAPPINGObject$fromJSON(jsonlite::toJSON(Data27Object$metrics, auto_unbox = TRUE))
      self$`eval_run` <- Data27Object$`eval_run`
      self$`eval_run_name` <- Data27Object$`eval_run_name`
      self$`artifacts_url` <- Data27Object$`artifacts_url`
    }
  )
)
