# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Data36 Class
#'
#' @field tags 
#' @field description 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Data36 <- R6::R6Class(
  'Data36',
  public = list(
    `tags` = NULL,
    `description` = NULL,
    initialize = function(`tags`, `description`){
      if (!missing(`tags`)) {
        stopifnot(is.list(`tags`), length(`tags`) != 0)
        lapply(`tags`, function(x) stopifnot(is.character(x)))
        self$`tags` <- `tags`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
    },
    toJSON = function() {
      Data36Object <- list()
      if (!is.null(self$`tags`)) {
        Data36Object[['tags']] <- self$`tags`
      }
      if (!is.null(self$`description`)) {
        Data36Object[['description']] <- self$`description`
      }

      Data36Object
    },
    fromJSON = function(Data36Json) {
      Data36Object <- jsonlite::fromJSON(Data36Json)
      if (!is.null(Data36Object$`tags`)) {
        self$`tags` <- Data36Object$`tags`
      }
      if (!is.null(Data36Object$`description`)) {
        self$`description` <- Data36Object$`description`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "tags": [%s],
           "description": %s
        }',
        lapply(self$`tags`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`description`
      )
    },
    fromJSONString = function(Data36Json) {
      Data36Object <- jsonlite::fromJSON(Data36Json)
      self$`tags` <- Data36Object$`tags`
      self$`description` <- Data36Object$`description`
    }
  )
)
