# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DatumSourceDetailsJob Class
#'
#' @field name 
#' @field jobid 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DatumSourceDetailsJob <- R6::R6Class(
  'DatumSourceDetailsJob',
  public = list(
    `name` = NULL,
    `jobid` = NULL,
    initialize = function(`name`, `jobid`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`jobid`)) {
        stopifnot(is.character(`jobid`), length(`jobid`) == 1)
        self$`jobid` <- `jobid`
      }
    },
    toJSON = function() {
      DatumSourceDetailsJobObject <- list()
      if (!is.null(self$`name`)) {
        DatumSourceDetailsJobObject[['name']] <- self$`name`
      }
      if (!is.null(self$`jobid`)) {
        DatumSourceDetailsJobObject[['jobid']] <- self$`jobid`
      }

      DatumSourceDetailsJobObject
    },
    fromJSON = function(DatumSourceDetailsJobJson) {
      DatumSourceDetailsJobObject <- jsonlite::fromJSON(DatumSourceDetailsJobJson)
      if (!is.null(DatumSourceDetailsJobObject$`name`)) {
        self$`name` <- DatumSourceDetailsJobObject$`name`
      }
      if (!is.null(DatumSourceDetailsJobObject$`jobid`)) {
        self$`jobid` <- DatumSourceDetailsJobObject$`jobid`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "jobid": %s
        }',
        self$`name`,
        self$`jobid`
      )
    },
    fromJSONString = function(DatumSourceDetailsJobJson) {
      DatumSourceDetailsJobObject <- jsonlite::fromJSON(DatumSourceDetailsJobJson)
      self$`name` <- DatumSourceDetailsJobObject$`name`
      self$`jobid` <- DatumSourceDetailsJobObject$`jobid`
    }
  )
)
