# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DatumJobDetails Class
#'
#' @field name 
#' @field user 
#' @field jobid 
#' @field class 
#' @field state 
#' @field tags 
#' @field pipeline 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DatumJobDetails <- R6::R6Class(
  'DatumJobDetails',
  public = list(
    `name` = NULL,
    `user` = NULL,
    `jobid` = NULL,
    `class` = NULL,
    `state` = NULL,
    `tags` = NULL,
    `pipeline` = NULL,
    initialize = function(`name`, `user`, `jobid`, `class`, `state`, `tags`, `pipeline`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`user`)) {
        stopifnot(is.character(`user`), length(`user`) == 1)
        self$`user` <- `user`
      }
      if (!missing(`jobid`)) {
        stopifnot(is.character(`jobid`), length(`jobid`) == 1)
        self$`jobid` <- `jobid`
      }
      if (!missing(`class`)) {
        stopifnot(is.character(`class`), length(`class`) == 1)
        self$`class` <- `class`
      }
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`tags`)) {
        stopifnot(is.list(`tags`), length(`tags`) != 0)
        lapply(`tags`, function(x) stopifnot(is.character(x)))
        self$`tags` <- `tags`
      }
      if (!missing(`pipeline`)) {
        stopifnot(R6::is.R6(`pipeline`))
        self$`pipeline` <- `pipeline`
      }
    },
    toJSON = function() {
      DatumJobDetailsObject <- list()
      if (!is.null(self$`name`)) {
        DatumJobDetailsObject[['name']] <- self$`name`
      }
      if (!is.null(self$`user`)) {
        DatumJobDetailsObject[['user']] <- self$`user`
      }
      if (!is.null(self$`jobid`)) {
        DatumJobDetailsObject[['jobid']] <- self$`jobid`
      }
      if (!is.null(self$`class`)) {
        DatumJobDetailsObject[['class']] <- self$`class`
      }
      if (!is.null(self$`state`)) {
        DatumJobDetailsObject[['state']] <- self$`state`
      }
      if (!is.null(self$`tags`)) {
        DatumJobDetailsObject[['tags']] <- self$`tags`
      }
      if (!is.null(self$`pipeline`)) {
        DatumJobDetailsObject[['pipeline']] <- self$`pipeline`$toJSON()
      }

      DatumJobDetailsObject
    },
    fromJSON = function(DatumJobDetailsJson) {
      DatumJobDetailsObject <- jsonlite::fromJSON(DatumJobDetailsJson)
      if (!is.null(DatumJobDetailsObject$`name`)) {
        self$`name` <- DatumJobDetailsObject$`name`
      }
      if (!is.null(DatumJobDetailsObject$`user`)) {
        self$`user` <- DatumJobDetailsObject$`user`
      }
      if (!is.null(DatumJobDetailsObject$`jobid`)) {
        self$`jobid` <- DatumJobDetailsObject$`jobid`
      }
      if (!is.null(DatumJobDetailsObject$`class`)) {
        self$`class` <- DatumJobDetailsObject$`class`
      }
      if (!is.null(DatumJobDetailsObject$`state`)) {
        self$`state` <- DatumJobDetailsObject$`state`
      }
      if (!is.null(DatumJobDetailsObject$`tags`)) {
        self$`tags` <- DatumJobDetailsObject$`tags`
      }
      if (!is.null(DatumJobDetailsObject$`pipeline`)) {
        pipelineObject <- DatumJobDetailsPipeline$new()
        pipelineObject$fromJSON(jsonlite::toJSON(DatumJobDetailsObject$pipeline, auto_unbox = TRUE))
        self$`pipeline` <- pipelineObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "user": %s,
           "jobid": %s,
           "class": %s,
           "state": %s,
           "tags": [%s],
           "pipeline": %s
        }',
        self$`name`,
        self$`user`,
        self$`jobid`,
        self$`class`,
        self$`state`,
        lapply(self$`tags`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`pipeline`$toJSON()
      )
    },
    fromJSONString = function(DatumJobDetailsJson) {
      DatumJobDetailsObject <- jsonlite::fromJSON(DatumJobDetailsJson)
      self$`name` <- DatumJobDetailsObject$`name`
      self$`user` <- DatumJobDetailsObject$`user`
      self$`jobid` <- DatumJobDetailsObject$`jobid`
      self$`class` <- DatumJobDetailsObject$`class`
      self$`state` <- DatumJobDetailsObject$`state`
      self$`tags` <- DatumJobDetailsObject$`tags`
      DatumJobDetailsPipelineObject <- DatumJobDetailsPipeline$new()
      self$`pipeline` <- DatumJobDetailsPipelineObject$fromJSON(jsonlite::toJSON(DatumJobDetailsObject$pipeline, auto_unbox = TRUE))
    }
  )
)
