# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DatumSourceDetails Class
#'
#' @field kind 
#' @field job 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DatumSourceDetails <- R6::R6Class(
  'DatumSourceDetails',
  public = list(
    `kind` = NULL,
    `job` = NULL,
    initialize = function(`kind`, `job`){
      if (!missing(`kind`)) {
        stopifnot(is.character(`kind`), length(`kind`) == 1)
        self$`kind` <- `kind`
      }
      if (!missing(`job`)) {
        stopifnot(R6::is.R6(`job`))
        self$`job` <- `job`
      }
    },
    toJSON = function() {
      DatumSourceDetailsObject <- list()
      if (!is.null(self$`kind`)) {
        DatumSourceDetailsObject[['kind']] <- self$`kind`
      }
      if (!is.null(self$`job`)) {
        DatumSourceDetailsObject[['job']] <- self$`job`$toJSON()
      }

      DatumSourceDetailsObject
    },
    fromJSON = function(DatumSourceDetailsJson) {
      DatumSourceDetailsObject <- jsonlite::fromJSON(DatumSourceDetailsJson)
      if (!is.null(DatumSourceDetailsObject$`kind`)) {
        self$`kind` <- DatumSourceDetailsObject$`kind`
      }
      if (!is.null(DatumSourceDetailsObject$`job`)) {
        jobObject <- DatumSourceDetailsJob$new()
        jobObject$fromJSON(jsonlite::toJSON(DatumSourceDetailsObject$job, auto_unbox = TRUE))
        self$`job` <- jobObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "kind": %s,
           "job": %s
        }',
        self$`kind`,
        self$`job`$toJSON()
      )
    },
    fromJSONString = function(DatumSourceDetailsJson) {
      DatumSourceDetailsObject <- jsonlite::fromJSON(DatumSourceDetailsJson)
      self$`kind` <- DatumSourceDetailsObject$`kind`
      DatumSourceDetailsJobObject <- DatumSourceDetailsJob$new()
      self$`job` <- DatumSourceDetailsJobObject$fromJSON(jsonlite::toJSON(DatumSourceDetailsObject$job, auto_unbox = TRUE))
    }
  )
)
