# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DkubeInfoCICD Class
#'
#' @field enabled 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DkubeInfoCICD <- R6::R6Class(
  'DkubeInfoCICD',
  public = list(
    `enabled` = NULL,
    initialize = function(`enabled`){
      if (!missing(`enabled`)) {
        stopifnot(is.character(`enabled`), length(`enabled`) == 1)
        self$`enabled` <- `enabled`
      }
    },
    toJSON = function() {
      DkubeInfoCICDObject <- list()
      if (!is.null(self$`enabled`)) {
        DkubeInfoCICDObject[['enabled']] <- self$`enabled`
      }

      DkubeInfoCICDObject
    },
    fromJSON = function(DkubeInfoCICDJson) {
      DkubeInfoCICDObject <- jsonlite::fromJSON(DkubeInfoCICDJson)
      if (!is.null(DkubeInfoCICDObject$`enabled`)) {
        self$`enabled` <- DkubeInfoCICDObject$`enabled`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "enabled": %s
        }',
        self$`enabled`
      )
    },
    fromJSONString = function(DkubeInfoCICDJson) {
      DkubeInfoCICDObject <- jsonlite::fromJSON(DkubeInfoCICDJson)
      self$`enabled` <- DkubeInfoCICDObject$`enabled`
    }
  )
)
