# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DkubeContainerModel Class
#'
#' @field framework 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DkubeContainerModel <- R6::R6Class(
  'DkubeContainerModel',
  public = list(
    `framework` = NULL,
    initialize = function(`framework`){
      if (!missing(`framework`)) {
        stopifnot(R6::is.R6(`framework`))
        self$`framework` <- `framework`
      }
    },
    toJSON = function() {
      DkubeContainerModelObject <- list()
      if (!is.null(self$`framework`)) {
        DkubeContainerModelObject[['framework']] <- self$`framework`$toJSON()
      }

      DkubeContainerModelObject
    },
    fromJSON = function(DkubeContainerModelJson) {
      DkubeContainerModelObject <- jsonlite::fromJSON(DkubeContainerModelJson)
      if (!is.null(DkubeContainerModelObject$`framework`)) {
        frameworkObject <- DkubeContainerModelFramework$new()
        frameworkObject$fromJSON(jsonlite::toJSON(DkubeContainerModelObject$framework, auto_unbox = TRUE))
        self$`framework` <- frameworkObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "framework": %s
        }',
        self$`framework`$toJSON()
      )
    },
    fromJSONString = function(DkubeContainerModelJson) {
      DkubeContainerModelObject <- jsonlite::fromJSON(DkubeContainerModelJson)
      DkubeContainerModelFrameworkObject <- DkubeContainerModelFramework$new()
      self$`framework` <- DkubeContainerModelFrameworkObject$fromJSON(jsonlite::toJSON(DkubeContainerModelObject$framework, auto_unbox = TRUE))
    }
  )
)
