# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DLSupport Class
#'
#' @field version 
#' @field frameworks 
#' @field tensorflow 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DLSupport <- R6::R6Class(
  'DLSupport',
  public = list(
    `version` = NULL,
    `frameworks` = NULL,
    `tensorflow` = NULL,
    initialize = function(`version`, `frameworks`, `tensorflow`){
      if (!missing(`version`)) {
        stopifnot(is.character(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
      if (!missing(`frameworks`)) {
        stopifnot(is.list(`frameworks`), length(`frameworks`) != 0)
        lapply(`frameworks`, function(x) stopifnot(is.character(x)))
        self$`frameworks` <- `frameworks`
      }
      if (!missing(`tensorflow`)) {
        stopifnot(R6::is.R6(`tensorflow`))
        self$`tensorflow` <- `tensorflow`
      }
    },
    toJSON = function() {
      DLSupportObject <- list()
      if (!is.null(self$`version`)) {
        DLSupportObject[['version']] <- self$`version`
      }
      if (!is.null(self$`frameworks`)) {
        DLSupportObject[['frameworks']] <- self$`frameworks`
      }
      if (!is.null(self$`tensorflow`)) {
        DLSupportObject[['tensorflow']] <- self$`tensorflow`$toJSON()
      }

      DLSupportObject
    },
    fromJSON = function(DLSupportJson) {
      DLSupportObject <- jsonlite::fromJSON(DLSupportJson)
      if (!is.null(DLSupportObject$`version`)) {
        self$`version` <- DLSupportObject$`version`
      }
      if (!is.null(DLSupportObject$`frameworks`)) {
        self$`frameworks` <- DLSupportObject$`frameworks`
      }
      if (!is.null(DLSupportObject$`tensorflow`)) {
        tensorflowObject <- DLSupportTensorflow$new()
        tensorflowObject$fromJSON(jsonlite::toJSON(DLSupportObject$tensorflow, auto_unbox = TRUE))
        self$`tensorflow` <- tensorflowObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "version": %s,
           "frameworks": [%s],
           "tensorflow": %s
        }',
        self$`version`,
        lapply(self$`frameworks`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`tensorflow`$toJSON()
      )
    },
    fromJSONString = function(DLSupportJson) {
      DLSupportObject <- jsonlite::fromJSON(DLSupportJson)
      self$`version` <- DLSupportObject$`version`
      self$`frameworks` <- DLSupportObject$`frameworks`
      DLSupportTensorflowObject <- DLSupportTensorflow$new()
      self$`tensorflow` <- DLSupportTensorflowObject$fromJSON(jsonlite::toJSON(DLSupportObject$tensorflow, auto_unbox = TRUE))
    }
  )
)
