# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DVSModel Class
#'
#' @field name 
#' @field uuid 
#' @field status 
#' @field metadata 
#' @field store 
#' @field git 
#' @field s3 
#' @field gcs 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DVSModel <- R6::R6Class(
  'DVSModel',
  public = list(
    `name` = NULL,
    `uuid` = NULL,
    `status` = NULL,
    `metadata` = NULL,
    `store` = NULL,
    `git` = NULL,
    `s3` = NULL,
    `gcs` = NULL,
    initialize = function(`name`, `uuid`, `status`, `metadata`, `store`, `git`, `s3`, `gcs`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`uuid`)) {
        stopifnot(is.character(`uuid`), length(`uuid`) == 1)
        self$`uuid` <- `uuid`
      }
      if (!missing(`status`)) {
        stopifnot(R6::is.R6(`status`))
        self$`status` <- `status`
      }
      if (!missing(`metadata`)) {
        stopifnot(is.character(`metadata`), length(`metadata`) == 1)
        self$`metadata` <- `metadata`
      }
      if (!missing(`store`)) {
        stopifnot(is.character(`store`), length(`store`) == 1)
        self$`store` <- `store`
      }
      if (!missing(`git`)) {
        stopifnot(R6::is.R6(`git`))
        self$`git` <- `git`
      }
      if (!missing(`s3`)) {
        stopifnot(R6::is.R6(`s3`))
        self$`s3` <- `s3`
      }
      if (!missing(`gcs`)) {
        stopifnot(R6::is.R6(`gcs`))
        self$`gcs` <- `gcs`
      }
    },
    toJSON = function() {
      DVSModelObject <- list()
      if (!is.null(self$`name`)) {
        DVSModelObject[['name']] <- self$`name`
      }
      if (!is.null(self$`uuid`)) {
        DVSModelObject[['uuid']] <- self$`uuid`
      }
      if (!is.null(self$`status`)) {
        DVSModelObject[['status']] <- self$`status`$toJSON()
      }
      if (!is.null(self$`metadata`)) {
        DVSModelObject[['metadata']] <- self$`metadata`
      }
      if (!is.null(self$`store`)) {
        DVSModelObject[['store']] <- self$`store`
      }
      if (!is.null(self$`git`)) {
        DVSModelObject[['git']] <- self$`git`$toJSON()
      }
      if (!is.null(self$`s3`)) {
        DVSModelObject[['s3']] <- self$`s3`$toJSON()
      }
      if (!is.null(self$`gcs`)) {
        DVSModelObject[['gcs']] <- self$`gcs`$toJSON()
      }

      DVSModelObject
    },
    fromJSON = function(DVSModelJson) {
      DVSModelObject <- jsonlite::fromJSON(DVSModelJson)
      if (!is.null(DVSModelObject$`name`)) {
        self$`name` <- DVSModelObject$`name`
      }
      if (!is.null(DVSModelObject$`uuid`)) {
        self$`uuid` <- DVSModelObject$`uuid`
      }
      if (!is.null(DVSModelObject$`status`)) {
        statusObject <- DVSModelStatus$new()
        statusObject$fromJSON(jsonlite::toJSON(DVSModelObject$status, auto_unbox = TRUE))
        self$`status` <- statusObject
      }
      if (!is.null(DVSModelObject$`metadata`)) {
        self$`metadata` <- DVSModelObject$`metadata`
      }
      if (!is.null(DVSModelObject$`store`)) {
        self$`store` <- DVSModelObject$`store`
      }
      if (!is.null(DVSModelObject$`git`)) {
        gitObject <- DVSModelGit$new()
        gitObject$fromJSON(jsonlite::toJSON(DVSModelObject$git, auto_unbox = TRUE))
        self$`git` <- gitObject
      }
      if (!is.null(DVSModelObject$`s3`)) {
        s3Object <- DVSModelS3$new()
        s3Object$fromJSON(jsonlite::toJSON(DVSModelObject$s3, auto_unbox = TRUE))
        self$`s3` <- s3Object
      }
      if (!is.null(DVSModelObject$`gcs`)) {
        gcsObject <- DVSModelGcs$new()
        gcsObject$fromJSON(jsonlite::toJSON(DVSModelObject$gcs, auto_unbox = TRUE))
        self$`gcs` <- gcsObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "uuid": %s,
           "status": %s,
           "metadata": %s,
           "store": %s,
           "git": %s,
           "s3": %s,
           "gcs": %s
        }',
        self$`name`,
        self$`uuid`,
        self$`status`$toJSON(),
        self$`metadata`,
        self$`store`,
        self$`git`$toJSON(),
        self$`s3`$toJSON(),
        self$`gcs`$toJSON()
      )
    },
    fromJSONString = function(DVSModelJson) {
      DVSModelObject <- jsonlite::fromJSON(DVSModelJson)
      self$`name` <- DVSModelObject$`name`
      self$`uuid` <- DVSModelObject$`uuid`
      DVSModelStatusObject <- DVSModelStatus$new()
      self$`status` <- DVSModelStatusObject$fromJSON(jsonlite::toJSON(DVSModelObject$status, auto_unbox = TRUE))
      self$`metadata` <- DVSModelObject$`metadata`
      self$`store` <- DVSModelObject$`store`
      DVSModelGitObject <- DVSModelGit$new()
      self$`git` <- DVSModelGitObject$fromJSON(jsonlite::toJSON(DVSModelObject$git, auto_unbox = TRUE))
      DVSModelS3Object <- DVSModelS3$new()
      self$`s3` <- DVSModelS3Object$fromJSON(jsonlite::toJSON(DVSModelObject$s3, auto_unbox = TRUE))
      DVSModelGcsObject <- DVSModelGcs$new()
      self$`gcs` <- DVSModelGcsObject$fromJSON(jsonlite::toJSON(DVSModelObject$gcs, auto_unbox = TRUE))
    }
  )
)
