# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DVSModelStatus Class
#'
#' @field state 
#' @field reason 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DVSModelStatus <- R6::R6Class(
  'DVSModelStatus',
  public = list(
    `state` = NULL,
    `reason` = NULL,
    initialize = function(`state`, `reason`){
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`reason`)) {
        stopifnot(is.character(`reason`), length(`reason`) == 1)
        self$`reason` <- `reason`
      }
    },
    toJSON = function() {
      DVSModelStatusObject <- list()
      if (!is.null(self$`state`)) {
        DVSModelStatusObject[['state']] <- self$`state`
      }
      if (!is.null(self$`reason`)) {
        DVSModelStatusObject[['reason']] <- self$`reason`
      }

      DVSModelStatusObject
    },
    fromJSON = function(DVSModelStatusJson) {
      DVSModelStatusObject <- jsonlite::fromJSON(DVSModelStatusJson)
      if (!is.null(DVSModelStatusObject$`state`)) {
        self$`state` <- DVSModelStatusObject$`state`
      }
      if (!is.null(DVSModelStatusObject$`reason`)) {
        self$`reason` <- DVSModelStatusObject$`reason`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "state": %s,
           "reason": %s
        }',
        self$`state`,
        self$`reason`
      )
    },
    fromJSONString = function(DVSModelStatusJson) {
      DVSModelStatusObject <- jsonlite::fromJSON(DVSModelStatusJson)
      self$`state` <- DVSModelStatusObject$`state`
      self$`reason` <- DVSModelStatusObject$`reason`
    }
  )
)
