# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' FeatureSetCommitDefJob Class
#'
#' @field kind 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FeatureSetCommitDefJob <- R6::R6Class(
  'FeatureSetCommitDefJob',
  public = list(
    `kind` = NULL,
    initialize = function(`kind`){
      if (!missing(`kind`)) {
        stopifnot(is.character(`kind`), length(`kind`) == 1)
        self$`kind` <- `kind`
      }
    },
    toJSON = function() {
      FeatureSetCommitDefJobObject <- list()
      if (!is.null(self$`kind`)) {
        FeatureSetCommitDefJobObject[['kind']] <- self$`kind`
      }

      FeatureSetCommitDefJobObject
    },
    fromJSON = function(FeatureSetCommitDefJobJson) {
      FeatureSetCommitDefJobObject <- jsonlite::fromJSON(FeatureSetCommitDefJobJson)
      if (!is.null(FeatureSetCommitDefJobObject$`kind`)) {
        self$`kind` <- FeatureSetCommitDefJobObject$`kind`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "kind": %s
        }',
        self$`kind`
      )
    },
    fromJSONString = function(FeatureSetCommitDefJobJson) {
      FeatureSetCommitDefJobObject <- jsonlite::fromJSON(FeatureSetCommitDefJobJson)
      self$`kind` <- FeatureSetCommitDefJobObject$`kind`
    }
  )
)
