# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' GitDetailsRepodetailsBranches Class
#'
#' @field name 
#' @field commits 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GitDetailsRepodetailsBranches <- R6::R6Class(
  'GitDetailsRepodetailsBranches',
  public = list(
    `name` = NULL,
    `commits` = NULL,
    initialize = function(`name`, `commits`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`commits`)) {
        stopifnot(is.list(`commits`), length(`commits`) != 0)
        lapply(`commits`, function(x) stopifnot(R6::is.R6(x)))
        self$`commits` <- `commits`
      }
    },
    toJSON = function() {
      GitDetailsRepodetailsBranchesObject <- list()
      if (!is.null(self$`name`)) {
        GitDetailsRepodetailsBranchesObject[['name']] <- self$`name`
      }
      if (!is.null(self$`commits`)) {
        GitDetailsRepodetailsBranchesObject[['commits']] <- lapply(self$`commits`, function(x) x$toJSON())
      }

      GitDetailsRepodetailsBranchesObject
    },
    fromJSON = function(GitDetailsRepodetailsBranchesJson) {
      GitDetailsRepodetailsBranchesObject <- jsonlite::fromJSON(GitDetailsRepodetailsBranchesJson)
      if (!is.null(GitDetailsRepodetailsBranchesObject$`name`)) {
        self$`name` <- GitDetailsRepodetailsBranchesObject$`name`
      }
      if (!is.null(GitDetailsRepodetailsBranchesObject$`commits`)) {
        self$`commits` <- lapply(GitDetailsRepodetailsBranchesObject$`commits`, function(x) {
          commitsObject <- GitCommitDetails$new()
          commitsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          commitsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "commits": [%s]
        }',
        self$`name`,
        lapply(self$`commits`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(GitDetailsRepodetailsBranchesJson) {
      GitDetailsRepodetailsBranchesObject <- jsonlite::fromJSON(GitDetailsRepodetailsBranchesJson)
      self$`name` <- GitDetailsRepodetailsBranchesObject$`name`
      self$`commits` <- lapply(GitDetailsRepodetailsBranchesObject$`commits`, function(x) GitCommitDetails$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
