# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' GroupModel Class
#'
#' @field version 
#' @field name 
#' @field providertype 
#' @field provider 
#' @field created_at 
#' @field generated 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GroupModel <- R6::R6Class(
  'GroupModel',
  public = list(
    `version` = NULL,
    `name` = NULL,
    `providertype` = NULL,
    `provider` = NULL,
    `created_at` = NULL,
    `generated` = NULL,
    initialize = function(`version`, `name`, `providertype`, `provider`, `created_at`, `generated`){
      if (!missing(`version`)) {
        stopifnot(is.character(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`providertype`)) {
        stopifnot(is.character(`providertype`), length(`providertype`) == 1)
        self$`providertype` <- `providertype`
      }
      if (!missing(`provider`)) {
        stopifnot(is.character(`provider`), length(`provider`) == 1)
        self$`provider` <- `provider`
      }
      if (!missing(`created_at`)) {
        stopifnot(R6::is.R6(`created_at`))
        self$`created_at` <- `created_at`
      }
      if (!missing(`generated`)) {
        stopifnot(R6::is.R6(`generated`))
        self$`generated` <- `generated`
      }
    },
    toJSON = function() {
      GroupModelObject <- list()
      if (!is.null(self$`version`)) {
        GroupModelObject[['version']] <- self$`version`
      }
      if (!is.null(self$`name`)) {
        GroupModelObject[['name']] <- self$`name`
      }
      if (!is.null(self$`providertype`)) {
        GroupModelObject[['providertype']] <- self$`providertype`
      }
      if (!is.null(self$`provider`)) {
        GroupModelObject[['provider']] <- self$`provider`
      }
      if (!is.null(self$`created_at`)) {
        GroupModelObject[['created_at']] <- self$`created_at`$toJSON()
      }
      if (!is.null(self$`generated`)) {
        GroupModelObject[['generated']] <- self$`generated`$toJSON()
      }

      GroupModelObject
    },
    fromJSON = function(GroupModelJson) {
      GroupModelObject <- jsonlite::fromJSON(GroupModelJson)
      if (!is.null(GroupModelObject$`version`)) {
        self$`version` <- GroupModelObject$`version`
      }
      if (!is.null(GroupModelObject$`name`)) {
        self$`name` <- GroupModelObject$`name`
      }
      if (!is.null(GroupModelObject$`providertype`)) {
        self$`providertype` <- GroupModelObject$`providertype`
      }
      if (!is.null(GroupModelObject$`provider`)) {
        self$`provider` <- GroupModelObject$`provider`
      }
      if (!is.null(GroupModelObject$`created_at`)) {
        created_atObject <- TimeStamps$new()
        created_atObject$fromJSON(jsonlite::toJSON(GroupModelObject$created_at, auto_unbox = TRUE))
        self$`created_at` <- created_atObject
      }
      if (!is.null(GroupModelObject$`generated`)) {
        generatedObject <- ModelCatalogItemGenerated$new()
        generatedObject$fromJSON(jsonlite::toJSON(GroupModelObject$generated, auto_unbox = TRUE))
        self$`generated` <- generatedObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "version": %s,
           "name": %s,
           "providertype": %s,
           "provider": %s,
           "created_at": %s,
           "generated": %s
        }',
        self$`version`,
        self$`name`,
        self$`providertype`,
        self$`provider`,
        self$`created_at`$toJSON(),
        self$`generated`$toJSON()
      )
    },
    fromJSONString = function(GroupModelJson) {
      GroupModelObject <- jsonlite::fromJSON(GroupModelJson)
      self$`version` <- GroupModelObject$`version`
      self$`name` <- GroupModelObject$`name`
      self$`providertype` <- GroupModelObject$`providertype`
      self$`provider` <- GroupModelObject$`provider`
      TimeStampsObject <- TimeStamps$new()
      self$`created_at` <- TimeStampsObject$fromJSON(jsonlite::toJSON(GroupModelObject$created_at, auto_unbox = TRUE))
      ModelCatalogItemGeneratedObject <- ModelCatalogItemGenerated$new()
      self$`generated` <- ModelCatalogItemGeneratedObject$fromJSON(jsonlite::toJSON(GroupModelObject$generated, auto_unbox = TRUE))
    }
  )
)
