# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' InlineResponse2009Data Class
#'
#' @field jwt 
#' @field role 
#' @field group 
#' @field username 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2009Data <- R6::R6Class(
  'InlineResponse2009Data',
  public = list(
    `jwt` = NULL,
    `role` = NULL,
    `group` = NULL,
    `username` = NULL,
    initialize = function(`jwt`, `role`, `group`, `username`){
      if (!missing(`jwt`)) {
        stopifnot(is.character(`jwt`), length(`jwt`) == 1)
        self$`jwt` <- `jwt`
      }
      if (!missing(`role`)) {
        stopifnot(is.character(`role`), length(`role`) == 1)
        self$`role` <- `role`
      }
      if (!missing(`group`)) {
        stopifnot(is.character(`group`), length(`group`) == 1)
        self$`group` <- `group`
      }
      if (!missing(`username`)) {
        stopifnot(is.character(`username`), length(`username`) == 1)
        self$`username` <- `username`
      }
    },
    toJSON = function() {
      InlineResponse2009DataObject <- list()
      if (!is.null(self$`jwt`)) {
        InlineResponse2009DataObject[['jwt']] <- self$`jwt`
      }
      if (!is.null(self$`role`)) {
        InlineResponse2009DataObject[['role']] <- self$`role`
      }
      if (!is.null(self$`group`)) {
        InlineResponse2009DataObject[['group']] <- self$`group`
      }
      if (!is.null(self$`username`)) {
        InlineResponse2009DataObject[['username']] <- self$`username`
      }

      InlineResponse2009DataObject
    },
    fromJSON = function(InlineResponse2009DataJson) {
      InlineResponse2009DataObject <- jsonlite::fromJSON(InlineResponse2009DataJson)
      if (!is.null(InlineResponse2009DataObject$`jwt`)) {
        self$`jwt` <- InlineResponse2009DataObject$`jwt`
      }
      if (!is.null(InlineResponse2009DataObject$`role`)) {
        self$`role` <- InlineResponse2009DataObject$`role`
      }
      if (!is.null(InlineResponse2009DataObject$`group`)) {
        self$`group` <- InlineResponse2009DataObject$`group`
      }
      if (!is.null(InlineResponse2009DataObject$`username`)) {
        self$`username` <- InlineResponse2009DataObject$`username`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "jwt": %s,
           "role": %s,
           "group": %s,
           "username": %s
        }',
        self$`jwt`,
        self$`role`,
        self$`group`,
        self$`username`
      )
    },
    fromJSONString = function(InlineResponse2009DataJson) {
      InlineResponse2009DataObject <- jsonlite::fromJSON(InlineResponse2009DataJson)
      self$`jwt` <- InlineResponse2009DataObject$`jwt`
      self$`role` <- InlineResponse2009DataObject$`role`
      self$`group` <- InlineResponse2009DataObject$`group`
      self$`username` <- InlineResponse2009DataObject$`username`
    }
  )
)
