# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' InlineResponse2005Data Class
#'
#' @field form 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse2005Data <- R6::R6Class(
  'InlineResponse2005Data',
  public = list(
    `form` = NULL,
    initialize = function(`form`){
      if (!missing(`form`)) {
        stopifnot(R6::is.R6(`form`))
        self$`form` <- `form`
      }
    },
    toJSON = function() {
      InlineResponse2005DataObject <- list()
      if (!is.null(self$`form`)) {
        InlineResponse2005DataObject[['form']] <- self$`form`$toJSON()
      }

      InlineResponse2005DataObject
    },
    fromJSON = function(InlineResponse2005DataJson) {
      InlineResponse2005DataObject <- jsonlite::fromJSON(InlineResponse2005DataJson)
      if (!is.null(InlineResponse2005DataObject$`form`)) {
        formObject <- JsonForm$new()
        formObject$fromJSON(jsonlite::toJSON(InlineResponse2005DataObject$form, auto_unbox = TRUE))
        self$`form` <- formObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "form": %s
        }',
        self$`form`$toJSON()
      )
    },
    fromJSONString = function(InlineResponse2005DataJson) {
      InlineResponse2005DataObject <- jsonlite::fromJSON(InlineResponse2005DataJson)
      JsonFormObject <- JsonForm$new()
      self$`form` <- JsonFormObject$fromJSON(jsonlite::toJSON(InlineResponse2005DataObject$form, auto_unbox = TRUE))
    }
  )
)
