# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' InlineResponse20021DataVersions Class
#'
#' @field version 
#' @field details 
#' @field jobs 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20021DataVersions <- R6::R6Class(
  'InlineResponse20021DataVersions',
  public = list(
    `version` = NULL,
    `details` = NULL,
    `jobs` = NULL,
    initialize = function(`version`, `details`, `jobs`){
      if (!missing(`version`)) {
        stopifnot(R6::is.R6(`version`))
        self$`version` <- `version`
      }
      if (!missing(`details`)) {
        stopifnot(R6::is.R6(`details`))
        self$`details` <- `details`
      }
      if (!missing(`jobs`)) {
        stopifnot(is.list(`jobs`), length(`jobs`) != 0)
        lapply(`jobs`, function(x) stopifnot(R6::is.R6(x)))
        self$`jobs` <- `jobs`
      }
    },
    toJSON = function() {
      InlineResponse20021DataVersionsObject <- list()
      if (!is.null(self$`version`)) {
        InlineResponse20021DataVersionsObject[['version']] <- self$`version`$toJSON()
      }
      if (!is.null(self$`details`)) {
        InlineResponse20021DataVersionsObject[['details']] <- self$`details`$toJSON()
      }
      if (!is.null(self$`jobs`)) {
        InlineResponse20021DataVersionsObject[['jobs']] <- lapply(self$`jobs`, function(x) x$toJSON())
      }

      InlineResponse20021DataVersionsObject
    },
    fromJSON = function(InlineResponse20021DataVersionsJson) {
      InlineResponse20021DataVersionsObject <- jsonlite::fromJSON(InlineResponse20021DataVersionsJson)
      if (!is.null(InlineResponse20021DataVersionsObject$`version`)) {
        versionObject <- VersionModel$new()
        versionObject$fromJSON(jsonlite::toJSON(InlineResponse20021DataVersionsObject$version, auto_unbox = TRUE))
        self$`version` <- versionObject
      }
      if (!is.null(InlineResponse20021DataVersionsObject$`details`)) {
        detailsObject <- VersionDetails$new()
        detailsObject$fromJSON(jsonlite::toJSON(InlineResponse20021DataVersionsObject$details, auto_unbox = TRUE))
        self$`details` <- detailsObject
      }
      if (!is.null(InlineResponse20021DataVersionsObject$`jobs`)) {
        self$`jobs` <- lapply(InlineResponse20021DataVersionsObject$`jobs`, function(x) {
          jobsObject <- DatumJobDetails$new()
          jobsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          jobsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "version": %s,
           "details": %s,
           "jobs": [%s]
        }',
        self$`version`$toJSON(),
        self$`details`$toJSON(),
        lapply(self$`jobs`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(InlineResponse20021DataVersionsJson) {
      InlineResponse20021DataVersionsObject <- jsonlite::fromJSON(InlineResponse20021DataVersionsJson)
      VersionModelObject <- VersionModel$new()
      self$`version` <- VersionModelObject$fromJSON(jsonlite::toJSON(InlineResponse20021DataVersionsObject$version, auto_unbox = TRUE))
      VersionDetailsObject <- VersionDetails$new()
      self$`details` <- VersionDetailsObject$fromJSON(jsonlite::toJSON(InlineResponse20021DataVersionsObject$details, auto_unbox = TRUE))
      self$`jobs` <- lapply(InlineResponse20021DataVersionsObject$`jobs`, function(x) DatumJobDetails$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
