# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' InlineResponse20036Data Class
#'
#' @field class 
#' @field jobs 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20036Data <- R6::R6Class(
  'InlineResponse20036Data',
  public = list(
    `class` = NULL,
    `jobs` = NULL,
    initialize = function(`class`, `jobs`){
      if (!missing(`class`)) {
        stopifnot(is.character(`class`), length(`class`) == 1)
        self$`class` <- `class`
      }
      if (!missing(`jobs`)) {
        stopifnot(is.list(`jobs`), length(`jobs`) != 0)
        lapply(`jobs`, function(x) stopifnot(R6::is.R6(x)))
        self$`jobs` <- `jobs`
      }
    },
    toJSON = function() {
      InlineResponse20036DataObject <- list()
      if (!is.null(self$`class`)) {
        InlineResponse20036DataObject[['class']] <- self$`class`
      }
      if (!is.null(self$`jobs`)) {
        InlineResponse20036DataObject[['jobs']] <- lapply(self$`jobs`, function(x) x$toJSON())
      }

      InlineResponse20036DataObject
    },
    fromJSON = function(InlineResponse20036DataJson) {
      InlineResponse20036DataObject <- jsonlite::fromJSON(InlineResponse20036DataJson)
      if (!is.null(InlineResponse20036DataObject$`class`)) {
        self$`class` <- InlineResponse20036DataObject$`class`
      }
      if (!is.null(InlineResponse20036DataObject$`jobs`)) {
        self$`jobs` <- lapply(InlineResponse20036DataObject$`jobs`, function(x) {
          jobsObject <- JobCollection$new()
          jobsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          jobsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "class": %s,
           "jobs": [%s]
        }',
        self$`class`,
        lapply(self$`jobs`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(InlineResponse20036DataJson) {
      InlineResponse20036DataObject <- jsonlite::fromJSON(InlineResponse20036DataJson)
      self$`class` <- InlineResponse20036DataObject$`class`
      self$`jobs` <- lapply(InlineResponse20036DataObject$`jobs`, function(x) JobCollection$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
