# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' JobClusterModel Class
#'
#' @field name 
#' @field kind 
#' @field scheduling_opts 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
JobClusterModel <- R6::R6Class(
  'JobClusterModel',
  public = list(
    `name` = NULL,
    `kind` = NULL,
    `scheduling_opts` = NULL,
    initialize = function(`name`, `kind`, `scheduling_opts`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`kind`)) {
        stopifnot(is.character(`kind`), length(`kind`) == 1)
        self$`kind` <- `kind`
      }
      if (!missing(`scheduling_opts`)) {
        stopifnot(R6::is.R6(`scheduling_opts`))
        self$`scheduling_opts` <- `scheduling_opts`
      }
    },
    toJSON = function() {
      JobClusterModelObject <- list()
      if (!is.null(self$`name`)) {
        JobClusterModelObject[['name']] <- self$`name`
      }
      if (!is.null(self$`kind`)) {
        JobClusterModelObject[['kind']] <- self$`kind`
      }
      if (!is.null(self$`scheduling_opts`)) {
        JobClusterModelObject[['scheduling_opts']] <- self$`scheduling_opts`$toJSON()
      }

      JobClusterModelObject
    },
    fromJSON = function(JobClusterModelJson) {
      JobClusterModelObject <- jsonlite::fromJSON(JobClusterModelJson)
      if (!is.null(JobClusterModelObject$`name`)) {
        self$`name` <- JobClusterModelObject$`name`
      }
      if (!is.null(JobClusterModelObject$`kind`)) {
        self$`kind` <- JobClusterModelObject$`kind`
      }
      if (!is.null(JobClusterModelObject$`scheduling_opts`)) {
        scheduling_optsObject <- JobClusterModelSchedulingOpts$new()
        scheduling_optsObject$fromJSON(jsonlite::toJSON(JobClusterModelObject$scheduling_opts, auto_unbox = TRUE))
        self$`scheduling_opts` <- scheduling_optsObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "kind": %s,
           "scheduling_opts": %s
        }',
        self$`name`,
        self$`kind`,
        self$`scheduling_opts`$toJSON()
      )
    },
    fromJSONString = function(JobClusterModelJson) {
      JobClusterModelObject <- jsonlite::fromJSON(JobClusterModelJson)
      self$`name` <- JobClusterModelObject$`name`
      self$`kind` <- JobClusterModelObject$`kind`
      JobClusterModelSchedulingOptsObject <- JobClusterModelSchedulingOpts$new()
      self$`scheduling_opts` <- JobClusterModelSchedulingOptsObject$fromJSON(jsonlite::toJSON(JobClusterModelObject$scheduling_opts, auto_unbox = TRUE))
    }
  )
)
