# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' JobGroupModel Class
#'
#' @field name 
#' @field description 
#' @field generated 
#' @field user 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
JobGroupModel <- R6::R6Class(
  'JobGroupModel',
  public = list(
    `name` = NULL,
    `description` = NULL,
    `generated` = NULL,
    `user` = NULL,
    initialize = function(`name`, `description`, `generated`, `user`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`generated`)) {
        stopifnot(R6::is.R6(`generated`))
        self$`generated` <- `generated`
      }
      if (!missing(`user`)) {
        stopifnot(is.character(`user`), length(`user`) == 1)
        self$`user` <- `user`
      }
    },
    toJSON = function() {
      JobGroupModelObject <- list()
      if (!is.null(self$`name`)) {
        JobGroupModelObject[['name']] <- self$`name`
      }
      if (!is.null(self$`description`)) {
        JobGroupModelObject[['description']] <- self$`description`
      }
      if (!is.null(self$`generated`)) {
        JobGroupModelObject[['generated']] <- self$`generated`$toJSON()
      }
      if (!is.null(self$`user`)) {
        JobGroupModelObject[['user']] <- self$`user`
      }

      JobGroupModelObject
    },
    fromJSON = function(JobGroupModelJson) {
      JobGroupModelObject <- jsonlite::fromJSON(JobGroupModelJson)
      if (!is.null(JobGroupModelObject$`name`)) {
        self$`name` <- JobGroupModelObject$`name`
      }
      if (!is.null(JobGroupModelObject$`description`)) {
        self$`description` <- JobGroupModelObject$`description`
      }
      if (!is.null(JobGroupModelObject$`generated`)) {
        generatedObject <- JobGroupModelGenerated$new()
        generatedObject$fromJSON(jsonlite::toJSON(JobGroupModelObject$generated, auto_unbox = TRUE))
        self$`generated` <- generatedObject
      }
      if (!is.null(JobGroupModelObject$`user`)) {
        self$`user` <- JobGroupModelObject$`user`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "description": %s,
           "generated": %s,
           "user": %s
        }',
        self$`name`,
        self$`description`,
        self$`generated`$toJSON(),
        self$`user`
      )
    },
    fromJSONString = function(JobGroupModelJson) {
      JobGroupModelObject <- jsonlite::fromJSON(JobGroupModelJson)
      self$`name` <- JobGroupModelObject$`name`
      self$`description` <- JobGroupModelObject$`description`
      JobGroupModelGeneratedObject <- JobGroupModelGenerated$new()
      self$`generated` <- JobGroupModelGeneratedObject$fromJSON(jsonlite::toJSON(JobGroupModelObject$generated, auto_unbox = TRUE))
      self$`user` <- JobGroupModelObject$`user`
    }
  )
)
