# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' JobInputFeaturesetModel Class
#'
#' @field name 
#' @field version 
#' @field owner 
#' @field mountpath 
#' @field version_name 
#' @field job_added 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
JobInputFeaturesetModel <- R6::R6Class(
  'JobInputFeaturesetModel',
  public = list(
    `name` = NULL,
    `version` = NULL,
    `owner` = NULL,
    `mountpath` = NULL,
    `version_name` = NULL,
    `job_added` = NULL,
    initialize = function(`name`, `version`, `owner`, `mountpath`, `version_name`, `job_added`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`version`)) {
        stopifnot(is.character(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
      if (!missing(`owner`)) {
        stopifnot(is.character(`owner`), length(`owner`) == 1)
        self$`owner` <- `owner`
      }
      if (!missing(`mountpath`)) {
        stopifnot(is.character(`mountpath`), length(`mountpath`) == 1)
        self$`mountpath` <- `mountpath`
      }
      if (!missing(`version_name`)) {
        stopifnot(is.character(`version_name`), length(`version_name`) == 1)
        self$`version_name` <- `version_name`
      }
      if (!missing(`job_added`)) {
        self$`job_added` <- `job_added`
      }
    },
    toJSON = function() {
      JobInputFeaturesetModelObject <- list()
      if (!is.null(self$`name`)) {
        JobInputFeaturesetModelObject[['name']] <- self$`name`
      }
      if (!is.null(self$`version`)) {
        JobInputFeaturesetModelObject[['version']] <- self$`version`
      }
      if (!is.null(self$`owner`)) {
        JobInputFeaturesetModelObject[['owner']] <- self$`owner`
      }
      if (!is.null(self$`mountpath`)) {
        JobInputFeaturesetModelObject[['mountpath']] <- self$`mountpath`
      }
      if (!is.null(self$`version_name`)) {
        JobInputFeaturesetModelObject[['version_name']] <- self$`version_name`
      }
      if (!is.null(self$`job_added`)) {
        JobInputFeaturesetModelObject[['job_added']] <- self$`job_added`
      }

      JobInputFeaturesetModelObject
    },
    fromJSON = function(JobInputFeaturesetModelJson) {
      JobInputFeaturesetModelObject <- jsonlite::fromJSON(JobInputFeaturesetModelJson)
      if (!is.null(JobInputFeaturesetModelObject$`name`)) {
        self$`name` <- JobInputFeaturesetModelObject$`name`
      }
      if (!is.null(JobInputFeaturesetModelObject$`version`)) {
        self$`version` <- JobInputFeaturesetModelObject$`version`
      }
      if (!is.null(JobInputFeaturesetModelObject$`owner`)) {
        self$`owner` <- JobInputFeaturesetModelObject$`owner`
      }
      if (!is.null(JobInputFeaturesetModelObject$`mountpath`)) {
        self$`mountpath` <- JobInputFeaturesetModelObject$`mountpath`
      }
      if (!is.null(JobInputFeaturesetModelObject$`version_name`)) {
        self$`version_name` <- JobInputFeaturesetModelObject$`version_name`
      }
      if (!is.null(JobInputFeaturesetModelObject$`job_added`)) {
        self$`job_added` <- JobInputFeaturesetModelObject$`job_added`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "version": %s,
           "owner": %s,
           "mountpath": %s,
           "version_name": %s,
           "job_added": %s
        }',
        self$`name`,
        self$`version`,
        self$`owner`,
        self$`mountpath`,
        self$`version_name`,
        self$`job_added`
      )
    },
    fromJSONString = function(JobInputFeaturesetModelJson) {
      JobInputFeaturesetModelObject <- jsonlite::fromJSON(JobInputFeaturesetModelJson)
      self$`name` <- JobInputFeaturesetModelObject$`name`
      self$`version` <- JobInputFeaturesetModelObject$`version`
      self$`owner` <- JobInputFeaturesetModelObject$`owner`
      self$`mountpath` <- JobInputFeaturesetModelObject$`mountpath`
      self$`version_name` <- JobInputFeaturesetModelObject$`version_name`
      self$`job_added` <- JobInputFeaturesetModelObject$`job_added`
    }
  )
)
