# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' JobStatusModel Class
#'
#' @field sub_state 
#' @field state 
#' @field reason 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
JobStatusModel <- R6::R6Class(
  'JobStatusModel',
  public = list(
    `sub_state` = NULL,
    `state` = NULL,
    `reason` = NULL,
    initialize = function(`sub_state`, `state`, `reason`){
      if (!missing(`sub_state`)) {
        stopifnot(is.character(`sub_state`), length(`sub_state`) == 1)
        self$`sub_state` <- `sub_state`
      }
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`reason`)) {
        stopifnot(is.character(`reason`), length(`reason`) == 1)
        self$`reason` <- `reason`
      }
    },
    toJSON = function() {
      JobStatusModelObject <- list()
      if (!is.null(self$`sub_state`)) {
        JobStatusModelObject[['sub_state']] <- self$`sub_state`
      }
      if (!is.null(self$`state`)) {
        JobStatusModelObject[['state']] <- self$`state`
      }
      if (!is.null(self$`reason`)) {
        JobStatusModelObject[['reason']] <- self$`reason`
      }

      JobStatusModelObject
    },
    fromJSON = function(JobStatusModelJson) {
      JobStatusModelObject <- jsonlite::fromJSON(JobStatusModelJson)
      if (!is.null(JobStatusModelObject$`sub_state`)) {
        self$`sub_state` <- JobStatusModelObject$`sub_state`
      }
      if (!is.null(JobStatusModelObject$`state`)) {
        self$`state` <- JobStatusModelObject$`state`
      }
      if (!is.null(JobStatusModelObject$`reason`)) {
        self$`reason` <- JobStatusModelObject$`reason`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "sub_state": %s,
           "state": %s,
           "reason": %s
        }',
        self$`sub_state`,
        self$`state`,
        self$`reason`
      )
    },
    fromJSONString = function(JobStatusModelJson) {
      JobStatusModelObject <- jsonlite::fromJSON(JobStatusModelJson)
      self$`sub_state` <- JobStatusModelObject$`sub_state`
      self$`state` <- JobStatusModelObject$`state`
      self$`reason` <- JobStatusModelObject$`reason`
    }
  )
)
