# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' MigrationModelRemote Class
#'
#' @field url 
#' @field JWT 
#' @field user 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MigrationModelRemote <- R6::R6Class(
  'MigrationModelRemote',
  public = list(
    `url` = NULL,
    `JWT` = NULL,
    `user` = NULL,
    initialize = function(`url`, `JWT`, `user`){
      if (!missing(`url`)) {
        stopifnot(is.character(`url`), length(`url`) == 1)
        self$`url` <- `url`
      }
      if (!missing(`JWT`)) {
        stopifnot(is.character(`JWT`), length(`JWT`) == 1)
        self$`JWT` <- `JWT`
      }
      if (!missing(`user`)) {
        stopifnot(is.character(`user`), length(`user`) == 1)
        self$`user` <- `user`
      }
    },
    toJSON = function() {
      MigrationModelRemoteObject <- list()
      if (!is.null(self$`url`)) {
        MigrationModelRemoteObject[['url']] <- self$`url`
      }
      if (!is.null(self$`JWT`)) {
        MigrationModelRemoteObject[['JWT']] <- self$`JWT`
      }
      if (!is.null(self$`user`)) {
        MigrationModelRemoteObject[['user']] <- self$`user`
      }

      MigrationModelRemoteObject
    },
    fromJSON = function(MigrationModelRemoteJson) {
      MigrationModelRemoteObject <- jsonlite::fromJSON(MigrationModelRemoteJson)
      if (!is.null(MigrationModelRemoteObject$`url`)) {
        self$`url` <- MigrationModelRemoteObject$`url`
      }
      if (!is.null(MigrationModelRemoteObject$`JWT`)) {
        self$`JWT` <- MigrationModelRemoteObject$`JWT`
      }
      if (!is.null(MigrationModelRemoteObject$`user`)) {
        self$`user` <- MigrationModelRemoteObject$`user`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "url": %s,
           "JWT": %s,
           "user": %s
        }',
        self$`url`,
        self$`JWT`,
        self$`user`
      )
    },
    fromJSONString = function(MigrationModelRemoteJson) {
      MigrationModelRemoteObject <- jsonlite::fromJSON(MigrationModelRemoteJson)
      self$`url` <- MigrationModelRemoteObject$`url`
      self$`JWT` <- MigrationModelRemoteObject$`JWT`
      self$`user` <- MigrationModelRemoteObject$`user`
    }
  )
)
