# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' MigrationJobStatus Class
#'
#' @field job 
#' @field datums 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MigrationJobStatus <- R6::R6Class(
  'MigrationJobStatus',
  public = list(
    `job` = NULL,
    `datums` = NULL,
    initialize = function(`job`, `datums`){
      if (!missing(`job`)) {
        stopifnot(R6::is.R6(`job`))
        self$`job` <- `job`
      }
      if (!missing(`datums`)) {
        stopifnot(is.list(`datums`), length(`datums`) != 0)
        lapply(`datums`, function(x) stopifnot(R6::is.R6(x)))
        self$`datums` <- `datums`
      }
    },
    toJSON = function() {
      MigrationJobStatusObject <- list()
      if (!is.null(self$`job`)) {
        MigrationJobStatusObject[['job']] <- self$`job`$toJSON()
      }
      if (!is.null(self$`datums`)) {
        MigrationJobStatusObject[['datums']] <- lapply(self$`datums`, function(x) x$toJSON())
      }

      MigrationJobStatusObject
    },
    fromJSON = function(MigrationJobStatusJson) {
      MigrationJobStatusObject <- jsonlite::fromJSON(MigrationJobStatusJson)
      if (!is.null(MigrationJobStatusObject$`job`)) {
        jobObject <- MigrationJobModel$new()
        jobObject$fromJSON(jsonlite::toJSON(MigrationJobStatusObject$job, auto_unbox = TRUE))
        self$`job` <- jobObject
      }
      if (!is.null(MigrationJobStatusObject$`datums`)) {
        self$`datums` <- lapply(MigrationJobStatusObject$`datums`, function(x) {
          datumsObject <- MigrationDatumModel$new()
          datumsObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          datumsObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "job": %s,
           "datums": [%s]
        }',
        self$`job`$toJSON(),
        lapply(self$`datums`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(MigrationJobStatusJson) {
      MigrationJobStatusObject <- jsonlite::fromJSON(MigrationJobStatusJson)
      MigrationJobModelObject <- MigrationJobModel$new()
      self$`job` <- MigrationJobModelObject$fromJSON(jsonlite::toJSON(MigrationJobStatusObject$job, auto_unbox = TRUE))
      self$`datums` <- lapply(MigrationJobStatusObject$`datums`, function(x) MigrationDatumModel$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
