# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ModelMetrics Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModelMetrics <- R6::R6Class(
  'ModelMetrics',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      ModelMetricsObject <- list()

      ModelMetricsObject
    },
    fromJSON = function(ModelMetricsJson) {
      ModelMetricsObject <- jsonlite::fromJSON(ModelMetricsJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(ModelMetricsJson) {
      ModelMetricsObject <- jsonlite::fromJSON(ModelMetricsJson)
    }
  )
)
