# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ModelTrainingInfoDatasets Class
#'
#' @field name 
#' @field source_details 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModelTrainingInfoDatasets <- R6::R6Class(
  'ModelTrainingInfoDatasets',
  public = list(
    `name` = NULL,
    `source_details` = NULL,
    initialize = function(`name`, `source_details`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`source_details`)) {
        stopifnot(R6::is.R6(`source_details`))
        self$`source_details` <- `source_details`
      }
    },
    toJSON = function() {
      ModelTrainingInfoDatasetsObject <- list()
      if (!is.null(self$`name`)) {
        ModelTrainingInfoDatasetsObject[['name']] <- self$`name`
      }
      if (!is.null(self$`source_details`)) {
        ModelTrainingInfoDatasetsObject[['source_details']] <- self$`source_details`$toJSON()
      }

      ModelTrainingInfoDatasetsObject
    },
    fromJSON = function(ModelTrainingInfoDatasetsJson) {
      ModelTrainingInfoDatasetsObject <- jsonlite::fromJSON(ModelTrainingInfoDatasetsJson)
      if (!is.null(ModelTrainingInfoDatasetsObject$`name`)) {
        self$`name` <- ModelTrainingInfoDatasetsObject$`name`
      }
      if (!is.null(ModelTrainingInfoDatasetsObject$`source_details`)) {
        source_detailsObject <- ModelTrainingInfoDatasetsSourceDetails$new()
        source_detailsObject$fromJSON(jsonlite::toJSON(ModelTrainingInfoDatasetsObject$source_details, auto_unbox = TRUE))
        self$`source_details` <- source_detailsObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "source_details": %s
        }',
        self$`name`,
        self$`source_details`$toJSON()
      )
    },
    fromJSONString = function(ModelTrainingInfoDatasetsJson) {
      ModelTrainingInfoDatasetsObject <- jsonlite::fromJSON(ModelTrainingInfoDatasetsJson)
      self$`name` <- ModelTrainingInfoDatasetsObject$`name`
      ModelTrainingInfoDatasetsSourceDetailsObject <- ModelTrainingInfoDatasetsSourceDetails$new()
      self$`source_details` <- ModelTrainingInfoDatasetsSourceDetailsObject$fromJSON(jsonlite::toJSON(ModelTrainingInfoDatasetsObject$source_details, auto_unbox = TRUE))
    }
  )
)
