# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ModelServingInfo Class
#'
#' @field images 
#' @field transformer_code 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModelServingInfo <- R6::R6Class(
  'ModelServingInfo',
  public = list(
    `images` = NULL,
    `transformer_code` = NULL,
    initialize = function(`images`, `transformer_code`){
      if (!missing(`images`)) {
        stopifnot(R6::is.R6(`images`))
        self$`images` <- `images`
      }
      if (!missing(`transformer_code`)) {
        stopifnot(R6::is.R6(`transformer_code`))
        self$`transformer_code` <- `transformer_code`
      }
    },
    toJSON = function() {
      ModelServingInfoObject <- list()
      if (!is.null(self$`images`)) {
        ModelServingInfoObject[['images']] <- self$`images`$toJSON()
      }
      if (!is.null(self$`transformer_code`)) {
        ModelServingInfoObject[['transformer_code']] <- self$`transformer_code`$toJSON()
      }

      ModelServingInfoObject
    },
    fromJSON = function(ModelServingInfoJson) {
      ModelServingInfoObject <- jsonlite::fromJSON(ModelServingInfoJson)
      if (!is.null(ModelServingInfoObject$`images`)) {
        imagesObject <- ModelServingInfoImages$new()
        imagesObject$fromJSON(jsonlite::toJSON(ModelServingInfoObject$images, auto_unbox = TRUE))
        self$`images` <- imagesObject
      }
      if (!is.null(ModelServingInfoObject$`transformer_code`)) {
        transformer_codeObject <- ModelServingInfoTransformerCode$new()
        transformer_codeObject$fromJSON(jsonlite::toJSON(ModelServingInfoObject$transformer_code, auto_unbox = TRUE))
        self$`transformer_code` <- transformer_codeObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "images": %s,
           "transformer_code": %s
        }',
        self$`images`$toJSON(),
        self$`transformer_code`$toJSON()
      )
    },
    fromJSONString = function(ModelServingInfoJson) {
      ModelServingInfoObject <- jsonlite::fromJSON(ModelServingInfoJson)
      ModelServingInfoImagesObject <- ModelServingInfoImages$new()
      self$`images` <- ModelServingInfoImagesObject$fromJSON(jsonlite::toJSON(ModelServingInfoObject$images, auto_unbox = TRUE))
      ModelServingInfoTransformerCodeObject <- ModelServingInfoTransformerCode$new()
      self$`transformer_code` <- ModelServingInfoTransformerCodeObject$fromJSON(jsonlite::toJSON(ModelServingInfoObject$transformer_code, auto_unbox = TRUE))
    }
  )
)
