# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ModelDetailsUnsupported Class
#'
#' @field reason 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModelDetailsUnsupported <- R6::R6Class(
  'ModelDetailsUnsupported',
  public = list(
    `reason` = NULL,
    initialize = function(`reason`){
      if (!missing(`reason`)) {
        stopifnot(is.character(`reason`), length(`reason`) == 1)
        self$`reason` <- `reason`
      }
    },
    toJSON = function() {
      ModelDetailsUnsupportedObject <- list()
      if (!is.null(self$`reason`)) {
        ModelDetailsUnsupportedObject[['reason']] <- self$`reason`
      }

      ModelDetailsUnsupportedObject
    },
    fromJSON = function(ModelDetailsUnsupportedJson) {
      ModelDetailsUnsupportedObject <- jsonlite::fromJSON(ModelDetailsUnsupportedJson)
      if (!is.null(ModelDetailsUnsupportedObject$`reason`)) {
        self$`reason` <- ModelDetailsUnsupportedObject$`reason`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "reason": %s
        }',
        self$`reason`
      )
    },
    fromJSONString = function(ModelDetailsUnsupportedJson) {
      ModelDetailsUnsupportedObject <- jsonlite::fromJSON(ModelDetailsUnsupportedJson)
      self$`reason` <- ModelDetailsUnsupportedObject$`reason`
    }
  )
)
