# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ModelTrainingInfoFeaturesets Class
#'
#' @field name 
#' @field version 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModelTrainingInfoFeaturesets <- R6::R6Class(
  'ModelTrainingInfoFeaturesets',
  public = list(
    `name` = NULL,
    `version` = NULL,
    initialize = function(`name`, `version`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`version`)) {
        stopifnot(is.character(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
    },
    toJSON = function() {
      ModelTrainingInfoFeaturesetsObject <- list()
      if (!is.null(self$`name`)) {
        ModelTrainingInfoFeaturesetsObject[['name']] <- self$`name`
      }
      if (!is.null(self$`version`)) {
        ModelTrainingInfoFeaturesetsObject[['version']] <- self$`version`
      }

      ModelTrainingInfoFeaturesetsObject
    },
    fromJSON = function(ModelTrainingInfoFeaturesetsJson) {
      ModelTrainingInfoFeaturesetsObject <- jsonlite::fromJSON(ModelTrainingInfoFeaturesetsJson)
      if (!is.null(ModelTrainingInfoFeaturesetsObject$`name`)) {
        self$`name` <- ModelTrainingInfoFeaturesetsObject$`name`
      }
      if (!is.null(ModelTrainingInfoFeaturesetsObject$`version`)) {
        self$`version` <- ModelTrainingInfoFeaturesetsObject$`version`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "version": %s
        }',
        self$`name`,
        self$`version`
      )
    },
    fromJSONString = function(ModelTrainingInfoFeaturesetsJson) {
      ModelTrainingInfoFeaturesetsObject <- jsonlite::fromJSON(ModelTrainingInfoFeaturesetsJson)
      self$`name` <- ModelTrainingInfoFeaturesetsObject$`name`
      self$`version` <- ModelTrainingInfoFeaturesetsObject$`version`
    }
  )
)
