# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ModeldeployEventData Class
#'
#' @field resources 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModeldeployEventData <- R6::R6Class(
  'ModeldeployEventData',
  public = list(
    `resources` = NULL,
    initialize = function(`resources`){
      if (!missing(`resources`)) {
        stopifnot(is.list(`resources`), length(`resources`) != 0)
        lapply(`resources`, function(x) stopifnot(R6::is.R6(x)))
        self$`resources` <- `resources`
      }
    },
    toJSON = function() {
      ModeldeployEventDataObject <- list()
      if (!is.null(self$`resources`)) {
        ModeldeployEventDataObject[['resources']] <- lapply(self$`resources`, function(x) x$toJSON())
      }

      ModeldeployEventDataObject
    },
    fromJSON = function(ModeldeployEventDataJson) {
      ModeldeployEventDataObject <- jsonlite::fromJSON(ModeldeployEventDataJson)
      if (!is.null(ModeldeployEventDataObject$`resources`)) {
        self$`resources` <- lapply(ModeldeployEventDataObject$`resources`, function(x) {
          resourcesObject <- ModeldeployEventDataResources$new()
          resourcesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          resourcesObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "resources": [%s]
        }',
        lapply(self$`resources`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(ModeldeployEventDataJson) {
      ModeldeployEventDataObject <- jsonlite::fromJSON(ModeldeployEventDataJson)
      self$`resources` <- lapply(ModeldeployEventDataObject$`resources`, function(x) ModeldeployEventDataResources$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
