# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ModelDetailsTensorpbDevices Class
#'
#' @field cpu 
#' @field gpu 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModelDetailsTensorpbDevices <- R6::R6Class(
  'ModelDetailsTensorpbDevices',
  public = list(
    `cpu` = NULL,
    `gpu` = NULL,
    initialize = function(`cpu`, `gpu`){
      if (!missing(`cpu`)) {
        self$`cpu` <- `cpu`
      }
      if (!missing(`gpu`)) {
        self$`gpu` <- `gpu`
      }
    },
    toJSON = function() {
      ModelDetailsTensorpbDevicesObject <- list()
      if (!is.null(self$`cpu`)) {
        ModelDetailsTensorpbDevicesObject[['cpu']] <- self$`cpu`
      }
      if (!is.null(self$`gpu`)) {
        ModelDetailsTensorpbDevicesObject[['gpu']] <- self$`gpu`
      }

      ModelDetailsTensorpbDevicesObject
    },
    fromJSON = function(ModelDetailsTensorpbDevicesJson) {
      ModelDetailsTensorpbDevicesObject <- jsonlite::fromJSON(ModelDetailsTensorpbDevicesJson)
      if (!is.null(ModelDetailsTensorpbDevicesObject$`cpu`)) {
        self$`cpu` <- ModelDetailsTensorpbDevicesObject$`cpu`
      }
      if (!is.null(ModelDetailsTensorpbDevicesObject$`gpu`)) {
        self$`gpu` <- ModelDetailsTensorpbDevicesObject$`gpu`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "cpu": %s,
           "gpu": %s
        }',
        self$`cpu`,
        self$`gpu`
      )
    },
    fromJSONString = function(ModelDetailsTensorpbDevicesJson) {
      ModelDetailsTensorpbDevicesObject <- jsonlite::fromJSON(ModelDetailsTensorpbDevicesJson)
      self$`cpu` <- ModelDetailsTensorpbDevicesObject$`cpu`
      self$`gpu` <- ModelDetailsTensorpbDevicesObject$`gpu`
    }
  )
)
