# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' NFSAccessInfo Class
#'
#' @field server 
#' @field path 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
NFSAccessInfo <- R6::R6Class(
  'NFSAccessInfo',
  public = list(
    `server` = NULL,
    `path` = NULL,
    initialize = function(`server`, `path`){
      if (!missing(`server`)) {
        stopifnot(is.character(`server`), length(`server`) == 1)
        self$`server` <- `server`
      }
      if (!missing(`path`)) {
        stopifnot(is.character(`path`), length(`path`) == 1)
        self$`path` <- `path`
      }
    },
    toJSON = function() {
      NFSAccessInfoObject <- list()
      if (!is.null(self$`server`)) {
        NFSAccessInfoObject[['server']] <- self$`server`
      }
      if (!is.null(self$`path`)) {
        NFSAccessInfoObject[['path']] <- self$`path`
      }

      NFSAccessInfoObject
    },
    fromJSON = function(NFSAccessInfoJson) {
      NFSAccessInfoObject <- jsonlite::fromJSON(NFSAccessInfoJson)
      if (!is.null(NFSAccessInfoObject$`server`)) {
        self$`server` <- NFSAccessInfoObject$`server`
      }
      if (!is.null(NFSAccessInfoObject$`path`)) {
        self$`path` <- NFSAccessInfoObject$`path`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "server": %s,
           "path": %s
        }',
        self$`server`,
        self$`path`
      )
    },
    fromJSONString = function(NFSAccessInfoJson) {
      NFSAccessInfoObject <- jsonlite::fromJSON(NFSAccessInfoJson)
      self$`server` <- NFSAccessInfoObject$`server`
      self$`path` <- NFSAccessInfoObject$`path`
    }
  )
)
