# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' NodeModelAccelerator Class
#'
#' @field healthy 
#' @field class 
#' @field name 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
NodeModelAccelerator <- R6::R6Class(
  'NodeModelAccelerator',
  public = list(
    `healthy` = NULL,
    `class` = NULL,
    `name` = NULL,
    initialize = function(`healthy`, `class`, `name`){
      if (!missing(`healthy`)) {
        self$`healthy` <- `healthy`
      }
      if (!missing(`class`)) {
        stopifnot(is.character(`class`), length(`class`) == 1)
        self$`class` <- `class`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      NodeModelAcceleratorObject <- list()
      if (!is.null(self$`healthy`)) {
        NodeModelAcceleratorObject[['healthy']] <- self$`healthy`
      }
      if (!is.null(self$`class`)) {
        NodeModelAcceleratorObject[['class']] <- self$`class`
      }
      if (!is.null(self$`name`)) {
        NodeModelAcceleratorObject[['name']] <- self$`name`
      }

      NodeModelAcceleratorObject
    },
    fromJSON = function(NodeModelAcceleratorJson) {
      NodeModelAcceleratorObject <- jsonlite::fromJSON(NodeModelAcceleratorJson)
      if (!is.null(NodeModelAcceleratorObject$`healthy`)) {
        self$`healthy` <- NodeModelAcceleratorObject$`healthy`
      }
      if (!is.null(NodeModelAcceleratorObject$`class`)) {
        self$`class` <- NodeModelAcceleratorObject$`class`
      }
      if (!is.null(NodeModelAcceleratorObject$`name`)) {
        self$`name` <- NodeModelAcceleratorObject$`name`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "healthy": %s,
           "class": %s,
           "name": %s
        }',
        self$`healthy`,
        self$`class`,
        self$`name`
      )
    },
    fromJSONString = function(NodeModelAcceleratorJson) {
      NodeModelAcceleratorObject <- jsonlite::fromJSON(NodeModelAcceleratorJson)
      self$`healthy` <- NodeModelAcceleratorObject$`healthy`
      self$`class` <- NodeModelAcceleratorObject$`class`
      self$`name` <- NodeModelAcceleratorObject$`name`
    }
  )
)
