# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' NodeModelNetwork Class
#'
#' @field hostname 
#' @field hostip 
#' @field hostmac 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
NodeModelNetwork <- R6::R6Class(
  'NodeModelNetwork',
  public = list(
    `hostname` = NULL,
    `hostip` = NULL,
    `hostmac` = NULL,
    initialize = function(`hostname`, `hostip`, `hostmac`){
      if (!missing(`hostname`)) {
        stopifnot(is.character(`hostname`), length(`hostname`) == 1)
        self$`hostname` <- `hostname`
      }
      if (!missing(`hostip`)) {
        stopifnot(is.character(`hostip`), length(`hostip`) == 1)
        self$`hostip` <- `hostip`
      }
      if (!missing(`hostmac`)) {
        stopifnot(is.character(`hostmac`), length(`hostmac`) == 1)
        self$`hostmac` <- `hostmac`
      }
    },
    toJSON = function() {
      NodeModelNetworkObject <- list()
      if (!is.null(self$`hostname`)) {
        NodeModelNetworkObject[['hostname']] <- self$`hostname`
      }
      if (!is.null(self$`hostip`)) {
        NodeModelNetworkObject[['hostip']] <- self$`hostip`
      }
      if (!is.null(self$`hostmac`)) {
        NodeModelNetworkObject[['hostmac']] <- self$`hostmac`
      }

      NodeModelNetworkObject
    },
    fromJSON = function(NodeModelNetworkJson) {
      NodeModelNetworkObject <- jsonlite::fromJSON(NodeModelNetworkJson)
      if (!is.null(NodeModelNetworkObject$`hostname`)) {
        self$`hostname` <- NodeModelNetworkObject$`hostname`
      }
      if (!is.null(NodeModelNetworkObject$`hostip`)) {
        self$`hostip` <- NodeModelNetworkObject$`hostip`
      }
      if (!is.null(NodeModelNetworkObject$`hostmac`)) {
        self$`hostmac` <- NodeModelNetworkObject$`hostmac`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "hostname": %s,
           "hostip": %s,
           "hostmac": %s
        }',
        self$`hostname`,
        self$`hostip`,
        self$`hostmac`
      )
    },
    fromJSONString = function(NodeModelNetworkJson) {
      NodeModelNetworkObject <- jsonlite::fromJSON(NodeModelNetworkJson)
      self$`hostname` <- NodeModelNetworkObject$`hostname`
      self$`hostip` <- NodeModelNetworkObject$`hostip`
      self$`hostmac` <- NodeModelNetworkObject$`hostmac`
    }
  )
)
