# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' NodeCollectionDevicesGpus Class
#'
#' @field healthy 
#' @field unhealthy 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
NodeCollectionDevicesGpus <- R6::R6Class(
  'NodeCollectionDevicesGpus',
  public = list(
    `healthy` = NULL,
    `unhealthy` = NULL,
    initialize = function(`healthy`, `unhealthy`){
      if (!missing(`healthy`)) {
        stopifnot(is.list(`healthy`), length(`healthy`) != 0)
        lapply(`healthy`, function(x) stopifnot(R6::is.R6(x)))
        self$`healthy` <- `healthy`
      }
      if (!missing(`unhealthy`)) {
        stopifnot(is.list(`unhealthy`), length(`unhealthy`) != 0)
        lapply(`unhealthy`, function(x) stopifnot(R6::is.R6(x)))
        self$`unhealthy` <- `unhealthy`
      }
    },
    toJSON = function() {
      NodeCollectionDevicesGpusObject <- list()
      if (!is.null(self$`healthy`)) {
        NodeCollectionDevicesGpusObject[['healthy']] <- lapply(self$`healthy`, function(x) x$toJSON())
      }
      if (!is.null(self$`unhealthy`)) {
        NodeCollectionDevicesGpusObject[['unhealthy']] <- lapply(self$`unhealthy`, function(x) x$toJSON())
      }

      NodeCollectionDevicesGpusObject
    },
    fromJSON = function(NodeCollectionDevicesGpusJson) {
      NodeCollectionDevicesGpusObject <- jsonlite::fromJSON(NodeCollectionDevicesGpusJson)
      if (!is.null(NodeCollectionDevicesGpusObject$`healthy`)) {
        self$`healthy` <- lapply(NodeCollectionDevicesGpusObject$`healthy`, function(x) {
          healthyObject <- DeviceModel$new()
          healthyObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          healthyObject
        })
      }
      if (!is.null(NodeCollectionDevicesGpusObject$`unhealthy`)) {
        self$`unhealthy` <- lapply(NodeCollectionDevicesGpusObject$`unhealthy`, function(x) {
          unhealthyObject <- DeviceModel$new()
          unhealthyObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          unhealthyObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "healthy": [%s],
           "unhealthy": [%s]
        }',
        lapply(self$`healthy`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`unhealthy`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(NodeCollectionDevicesGpusJson) {
      NodeCollectionDevicesGpusObject <- jsonlite::fromJSON(NodeCollectionDevicesGpusJson)
      self$`healthy` <- lapply(NodeCollectionDevicesGpusObject$`healthy`, function(x) DeviceModel$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`unhealthy` <- lapply(NodeCollectionDevicesGpusObject$`unhealthy`, function(x) DeviceModel$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
