# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' NotebookResultModel Class
#'
#' @field nburl 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
NotebookResultModel <- R6::R6Class(
  'NotebookResultModel',
  public = list(
    `nburl` = NULL,
    initialize = function(`nburl`){
      if (!missing(`nburl`)) {
        stopifnot(is.character(`nburl`), length(`nburl`) == 1)
        self$`nburl` <- `nburl`
      }
    },
    toJSON = function() {
      NotebookResultModelObject <- list()
      if (!is.null(self$`nburl`)) {
        NotebookResultModelObject[['nburl']] <- self$`nburl`
      }

      NotebookResultModelObject
    },
    fromJSON = function(NotebookResultModelJson) {
      NotebookResultModelObject <- jsonlite::fromJSON(NotebookResultModelJson)
      if (!is.null(NotebookResultModelObject$`nburl`)) {
        self$`nburl` <- NotebookResultModelObject$`nburl`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "nburl": %s
        }',
        self$`nburl`
      )
    },
    fromJSONString = function(NotebookResultModelJson) {
      NotebookResultModelObject <- jsonlite::fromJSON(NotebookResultModelJson)
      self$`nburl` <- NotebookResultModelObject$`nburl`
    }
  )
)
