# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' PluginStatusModel Class
#'
#' @field state 
#' @field reason 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PluginStatusModel <- R6::R6Class(
  'PluginStatusModel',
  public = list(
    `state` = NULL,
    `reason` = NULL,
    initialize = function(`state`, `reason`){
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`reason`)) {
        stopifnot(is.character(`reason`), length(`reason`) == 1)
        self$`reason` <- `reason`
      }
    },
    toJSON = function() {
      PluginStatusModelObject <- list()
      if (!is.null(self$`state`)) {
        PluginStatusModelObject[['state']] <- self$`state`
      }
      if (!is.null(self$`reason`)) {
        PluginStatusModelObject[['reason']] <- self$`reason`
      }

      PluginStatusModelObject
    },
    fromJSON = function(PluginStatusModelJson) {
      PluginStatusModelObject <- jsonlite::fromJSON(PluginStatusModelJson)
      if (!is.null(PluginStatusModelObject$`state`)) {
        self$`state` <- PluginStatusModelObject$`state`
      }
      if (!is.null(PluginStatusModelObject$`reason`)) {
        self$`reason` <- PluginStatusModelObject$`reason`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "state": %s,
           "reason": %s
        }',
        self$`state`,
        self$`reason`
      )
    },
    fromJSONString = function(PluginStatusModelJson) {
      PluginStatusModelObject <- jsonlite::fromJSON(PluginStatusModelJson)
      self$`state` <- PluginStatusModelObject$`state`
      self$`reason` <- PluginStatusModelObject$`reason`
    }
  )
)
