# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' PoolCollectionDevices Class
#'
#' @field inuse 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PoolCollectionDevices <- R6::R6Class(
  'PoolCollectionDevices',
  public = list(
    `inuse` = NULL,
    initialize = function(`inuse`){
      if (!missing(`inuse`)) {
        stopifnot(R6::is.R6(`inuse`))
        self$`inuse` <- `inuse`
      }
    },
    toJSON = function() {
      PoolCollectionDevicesObject <- list()
      if (!is.null(self$`inuse`)) {
        PoolCollectionDevicesObject[['inuse']] <- self$`inuse`$toJSON()
      }

      PoolCollectionDevicesObject
    },
    fromJSON = function(PoolCollectionDevicesJson) {
      PoolCollectionDevicesObject <- jsonlite::fromJSON(PoolCollectionDevicesJson)
      if (!is.null(PoolCollectionDevicesObject$`inuse`)) {
        inuseObject <- PoolCollectionDevicesInuse$new()
        inuseObject$fromJSON(jsonlite::toJSON(PoolCollectionDevicesObject$inuse, auto_unbox = TRUE))
        self$`inuse` <- inuseObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "inuse": %s
        }',
        self$`inuse`$toJSON()
      )
    },
    fromJSONString = function(PoolCollectionDevicesJson) {
      PoolCollectionDevicesObject <- jsonlite::fromJSON(PoolCollectionDevicesJson)
      PoolCollectionDevicesInuseObject <- PoolCollectionDevicesInuse$new()
      self$`inuse` <- PoolCollectionDevicesInuseObject$fromJSON(jsonlite::toJSON(PoolCollectionDevicesObject$inuse, auto_unbox = TRUE))
    }
  )
)
