# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' PoolCollectionDevicesInuse Class
#'
#' @field count 
#' @field devices 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PoolCollectionDevicesInuse <- R6::R6Class(
  'PoolCollectionDevicesInuse',
  public = list(
    `count` = NULL,
    `devices` = NULL,
    initialize = function(`count`, `devices`){
      if (!missing(`count`)) {
        stopifnot(is.numeric(`count`), length(`count`) == 1)
        self$`count` <- `count`
      }
      if (!missing(`devices`)) {
        stopifnot(is.list(`devices`), length(`devices`) != 0)
        lapply(`devices`, function(x) stopifnot(R6::is.R6(x)))
        self$`devices` <- `devices`
      }
    },
    toJSON = function() {
      PoolCollectionDevicesInuseObject <- list()
      if (!is.null(self$`count`)) {
        PoolCollectionDevicesInuseObject[['count']] <- self$`count`
      }
      if (!is.null(self$`devices`)) {
        PoolCollectionDevicesInuseObject[['devices']] <- lapply(self$`devices`, function(x) x$toJSON())
      }

      PoolCollectionDevicesInuseObject
    },
    fromJSON = function(PoolCollectionDevicesInuseJson) {
      PoolCollectionDevicesInuseObject <- jsonlite::fromJSON(PoolCollectionDevicesInuseJson)
      if (!is.null(PoolCollectionDevicesInuseObject$`count`)) {
        self$`count` <- PoolCollectionDevicesInuseObject$`count`
      }
      if (!is.null(PoolCollectionDevicesInuseObject$`devices`)) {
        self$`devices` <- lapply(PoolCollectionDevicesInuseObject$`devices`, function(x) {
          devicesObject <- DeviceModel$new()
          devicesObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          devicesObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "count": %d,
           "devices": [%s]
        }',
        self$`count`,
        lapply(self$`devices`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(PoolCollectionDevicesInuseJson) {
      PoolCollectionDevicesInuseObject <- jsonlite::fromJSON(PoolCollectionDevicesInuseJson)
      self$`count` <- PoolCollectionDevicesInuseObject$`count`
      self$`devices` <- lapply(PoolCollectionDevicesInuseObject$`devices`, function(x) DeviceModel$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
