# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ProjectUpdateModel Class
#'
#' @field name Name
#' @field description Description
#' @field image Image
#' @field leaderboard Leaderboard
#' @field details Project Details
#' @field eval_repo Eval Repo
#' @field eval_commit_id Eval Commit Id
#' @field eval_image Eval Image
#' @field eval_script Eval Script
#' @field eval_details Eval Details
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ProjectUpdateModel <- R6::R6Class(
  'ProjectUpdateModel',
  public = list(
    `name` = NULL,
    `description` = NULL,
    `image` = NULL,
    `leaderboard` = NULL,
    `details` = NULL,
    `eval_repo` = NULL,
    `eval_commit_id` = NULL,
    `eval_image` = NULL,
    `eval_script` = NULL,
    `eval_details` = NULL,
    initialize = function(`name`, `description`, `image`, `leaderboard`, `details`, `eval_repo`, `eval_commit_id`, `eval_image`, `eval_script`, `eval_details`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`image`)) {
        stopifnot(is.character(`image`), length(`image`) == 1)
        self$`image` <- `image`
      }
      if (!missing(`leaderboard`)) {
        self$`leaderboard` <- `leaderboard`
      }
      if (!missing(`details`)) {
        stopifnot(is.character(`details`), length(`details`) == 1)
        self$`details` <- `details`
      }
      if (!missing(`eval_repo`)) {
        stopifnot(is.character(`eval_repo`), length(`eval_repo`) == 1)
        self$`eval_repo` <- `eval_repo`
      }
      if (!missing(`eval_commit_id`)) {
        stopifnot(is.character(`eval_commit_id`), length(`eval_commit_id`) == 1)
        self$`eval_commit_id` <- `eval_commit_id`
      }
      if (!missing(`eval_image`)) {
        stopifnot(is.character(`eval_image`), length(`eval_image`) == 1)
        self$`eval_image` <- `eval_image`
      }
      if (!missing(`eval_script`)) {
        stopifnot(is.character(`eval_script`), length(`eval_script`) == 1)
        self$`eval_script` <- `eval_script`
      }
      if (!missing(`eval_details`)) {
        stopifnot(is.character(`eval_details`), length(`eval_details`) == 1)
        self$`eval_details` <- `eval_details`
      }
    },
    toJSON = function() {
      ProjectUpdateModelObject <- list()
      if (!is.null(self$`name`)) {
        ProjectUpdateModelObject[['name']] <- self$`name`
      }
      if (!is.null(self$`description`)) {
        ProjectUpdateModelObject[['description']] <- self$`description`
      }
      if (!is.null(self$`image`)) {
        ProjectUpdateModelObject[['image']] <- self$`image`
      }
      if (!is.null(self$`leaderboard`)) {
        ProjectUpdateModelObject[['leaderboard']] <- self$`leaderboard`
      }
      if (!is.null(self$`details`)) {
        ProjectUpdateModelObject[['details']] <- self$`details`
      }
      if (!is.null(self$`eval_repo`)) {
        ProjectUpdateModelObject[['eval_repo']] <- self$`eval_repo`
      }
      if (!is.null(self$`eval_commit_id`)) {
        ProjectUpdateModelObject[['eval_commit_id']] <- self$`eval_commit_id`
      }
      if (!is.null(self$`eval_image`)) {
        ProjectUpdateModelObject[['eval_image']] <- self$`eval_image`
      }
      if (!is.null(self$`eval_script`)) {
        ProjectUpdateModelObject[['eval_script']] <- self$`eval_script`
      }
      if (!is.null(self$`eval_details`)) {
        ProjectUpdateModelObject[['eval_details']] <- self$`eval_details`
      }

      ProjectUpdateModelObject
    },
    fromJSON = function(ProjectUpdateModelJson) {
      ProjectUpdateModelObject <- jsonlite::fromJSON(ProjectUpdateModelJson)
      if (!is.null(ProjectUpdateModelObject$`name`)) {
        self$`name` <- ProjectUpdateModelObject$`name`
      }
      if (!is.null(ProjectUpdateModelObject$`description`)) {
        self$`description` <- ProjectUpdateModelObject$`description`
      }
      if (!is.null(ProjectUpdateModelObject$`image`)) {
        self$`image` <- ProjectUpdateModelObject$`image`
      }
      if (!is.null(ProjectUpdateModelObject$`leaderboard`)) {
        self$`leaderboard` <- ProjectUpdateModelObject$`leaderboard`
      }
      if (!is.null(ProjectUpdateModelObject$`details`)) {
        self$`details` <- ProjectUpdateModelObject$`details`
      }
      if (!is.null(ProjectUpdateModelObject$`eval_repo`)) {
        self$`eval_repo` <- ProjectUpdateModelObject$`eval_repo`
      }
      if (!is.null(ProjectUpdateModelObject$`eval_commit_id`)) {
        self$`eval_commit_id` <- ProjectUpdateModelObject$`eval_commit_id`
      }
      if (!is.null(ProjectUpdateModelObject$`eval_image`)) {
        self$`eval_image` <- ProjectUpdateModelObject$`eval_image`
      }
      if (!is.null(ProjectUpdateModelObject$`eval_script`)) {
        self$`eval_script` <- ProjectUpdateModelObject$`eval_script`
      }
      if (!is.null(ProjectUpdateModelObject$`eval_details`)) {
        self$`eval_details` <- ProjectUpdateModelObject$`eval_details`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "description": %s,
           "image": %s,
           "leaderboard": %s,
           "details": %s,
           "eval_repo": %s,
           "eval_commit_id": %s,
           "eval_image": %s,
           "eval_script": %s,
           "eval_details": %s
        }',
        self$`name`,
        self$`description`,
        self$`image`,
        self$`leaderboard`,
        self$`details`,
        self$`eval_repo`,
        self$`eval_commit_id`,
        self$`eval_image`,
        self$`eval_script`,
        self$`eval_details`
      )
    },
    fromJSONString = function(ProjectUpdateModelJson) {
      ProjectUpdateModelObject <- jsonlite::fromJSON(ProjectUpdateModelJson)
      self$`name` <- ProjectUpdateModelObject$`name`
      self$`description` <- ProjectUpdateModelObject$`description`
      self$`image` <- ProjectUpdateModelObject$`image`
      self$`leaderboard` <- ProjectUpdateModelObject$`leaderboard`
      self$`details` <- ProjectUpdateModelObject$`details`
      self$`eval_repo` <- ProjectUpdateModelObject$`eval_repo`
      self$`eval_commit_id` <- ProjectUpdateModelObject$`eval_commit_id`
      self$`eval_image` <- ProjectUpdateModelObject$`eval_image`
      self$`eval_script` <- ProjectUpdateModelObject$`eval_script`
      self$`eval_details` <- ProjectUpdateModelObject$`eval_details`
    }
  )
)
