# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ReleasedModelItem Class
#'
#' @field name 
#' @field reason 
#' @field version 
#' @field user 
#' @field stage 
#' @field trackingURL 
#' @field UUID 
#' @field description 
#' @field releasedTimestamp 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ReleasedModelItem <- R6::R6Class(
  'ReleasedModelItem',
  public = list(
    `name` = NULL,
    `reason` = NULL,
    `version` = NULL,
    `user` = NULL,
    `stage` = NULL,
    `trackingURL` = NULL,
    `UUID` = NULL,
    `description` = NULL,
    `releasedTimestamp` = NULL,
    initialize = function(`name`, `reason`, `version`, `user`, `stage`, `trackingURL`, `UUID`, `description`, `releasedTimestamp`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`reason`)) {
        stopifnot(is.character(`reason`), length(`reason`) == 1)
        self$`reason` <- `reason`
      }
      if (!missing(`version`)) {
        stopifnot(is.character(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
      if (!missing(`user`)) {
        stopifnot(is.character(`user`), length(`user`) == 1)
        self$`user` <- `user`
      }
      if (!missing(`stage`)) {
        stopifnot(is.character(`stage`), length(`stage`) == 1)
        self$`stage` <- `stage`
      }
      if (!missing(`trackingURL`)) {
        stopifnot(is.character(`trackingURL`), length(`trackingURL`) == 1)
        self$`trackingURL` <- `trackingURL`
      }
      if (!missing(`UUID`)) {
        stopifnot(is.character(`UUID`), length(`UUID`) == 1)
        self$`UUID` <- `UUID`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`releasedTimestamp`)) {
        stopifnot(R6::is.R6(`releasedTimestamp`))
        self$`releasedTimestamp` <- `releasedTimestamp`
      }
    },
    toJSON = function() {
      ReleasedModelItemObject <- list()
      if (!is.null(self$`name`)) {
        ReleasedModelItemObject[['name']] <- self$`name`
      }
      if (!is.null(self$`reason`)) {
        ReleasedModelItemObject[['reason']] <- self$`reason`
      }
      if (!is.null(self$`version`)) {
        ReleasedModelItemObject[['version']] <- self$`version`
      }
      if (!is.null(self$`user`)) {
        ReleasedModelItemObject[['user']] <- self$`user`
      }
      if (!is.null(self$`stage`)) {
        ReleasedModelItemObject[['stage']] <- self$`stage`
      }
      if (!is.null(self$`trackingURL`)) {
        ReleasedModelItemObject[['trackingURL']] <- self$`trackingURL`
      }
      if (!is.null(self$`UUID`)) {
        ReleasedModelItemObject[['UUID']] <- self$`UUID`
      }
      if (!is.null(self$`description`)) {
        ReleasedModelItemObject[['description']] <- self$`description`
      }
      if (!is.null(self$`releasedTimestamp`)) {
        ReleasedModelItemObject[['releasedTimestamp']] <- self$`releasedTimestamp`$toJSON()
      }

      ReleasedModelItemObject
    },
    fromJSON = function(ReleasedModelItemJson) {
      ReleasedModelItemObject <- jsonlite::fromJSON(ReleasedModelItemJson)
      if (!is.null(ReleasedModelItemObject$`name`)) {
        self$`name` <- ReleasedModelItemObject$`name`
      }
      if (!is.null(ReleasedModelItemObject$`reason`)) {
        self$`reason` <- ReleasedModelItemObject$`reason`
      }
      if (!is.null(ReleasedModelItemObject$`version`)) {
        self$`version` <- ReleasedModelItemObject$`version`
      }
      if (!is.null(ReleasedModelItemObject$`user`)) {
        self$`user` <- ReleasedModelItemObject$`user`
      }
      if (!is.null(ReleasedModelItemObject$`stage`)) {
        self$`stage` <- ReleasedModelItemObject$`stage`
      }
      if (!is.null(ReleasedModelItemObject$`trackingURL`)) {
        self$`trackingURL` <- ReleasedModelItemObject$`trackingURL`
      }
      if (!is.null(ReleasedModelItemObject$`UUID`)) {
        self$`UUID` <- ReleasedModelItemObject$`UUID`
      }
      if (!is.null(ReleasedModelItemObject$`description`)) {
        self$`description` <- ReleasedModelItemObject$`description`
      }
      if (!is.null(ReleasedModelItemObject$`releasedTimestamp`)) {
        releasedTimestampObject <- TimeStamps$new()
        releasedTimestampObject$fromJSON(jsonlite::toJSON(ReleasedModelItemObject$releasedTimestamp, auto_unbox = TRUE))
        self$`releasedTimestamp` <- releasedTimestampObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "reason": %s,
           "version": %s,
           "user": %s,
           "stage": %s,
           "trackingURL": %s,
           "UUID": %s,
           "description": %s,
           "releasedTimestamp": %s
        }',
        self$`name`,
        self$`reason`,
        self$`version`,
        self$`user`,
        self$`stage`,
        self$`trackingURL`,
        self$`UUID`,
        self$`description`,
        self$`releasedTimestamp`$toJSON()
      )
    },
    fromJSONString = function(ReleasedModelItemJson) {
      ReleasedModelItemObject <- jsonlite::fromJSON(ReleasedModelItemJson)
      self$`name` <- ReleasedModelItemObject$`name`
      self$`reason` <- ReleasedModelItemObject$`reason`
      self$`version` <- ReleasedModelItemObject$`version`
      self$`user` <- ReleasedModelItemObject$`user`
      self$`stage` <- ReleasedModelItemObject$`stage`
      self$`trackingURL` <- ReleasedModelItemObject$`trackingURL`
      self$`UUID` <- ReleasedModelItemObject$`UUID`
      self$`description` <- ReleasedModelItemObject$`description`
      TimeStampsObject <- TimeStamps$new()
      self$`releasedTimestamp` <- TimeStampsObject$fromJSON(jsonlite::toJSON(ReleasedModelItemObject$releasedTimestamp, auto_unbox = TRUE))
    }
  )
)
