# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' TrackingModel Class
#'
#' @field runId 
#' @field artifactId 
#' @field versionId 
#' @field pipelineId 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TrackingModel <- R6::R6Class(
  'TrackingModel',
  public = list(
    `runId` = NULL,
    `artifactId` = NULL,
    `versionId` = NULL,
    `pipelineId` = NULL,
    initialize = function(`runId`, `artifactId`, `versionId`, `pipelineId`){
      if (!missing(`runId`)) {
        stopifnot(is.character(`runId`), length(`runId`) == 1)
        self$`runId` <- `runId`
      }
      if (!missing(`artifactId`)) {
        stopifnot(is.character(`artifactId`), length(`artifactId`) == 1)
        self$`artifactId` <- `artifactId`
      }
      if (!missing(`versionId`)) {
        stopifnot(is.character(`versionId`), length(`versionId`) == 1)
        self$`versionId` <- `versionId`
      }
      if (!missing(`pipelineId`)) {
        stopifnot(is.character(`pipelineId`), length(`pipelineId`) == 1)
        self$`pipelineId` <- `pipelineId`
      }
    },
    toJSON = function() {
      TrackingModelObject <- list()
      if (!is.null(self$`runId`)) {
        TrackingModelObject[['runId']] <- self$`runId`
      }
      if (!is.null(self$`artifactId`)) {
        TrackingModelObject[['artifactId']] <- self$`artifactId`
      }
      if (!is.null(self$`versionId`)) {
        TrackingModelObject[['versionId']] <- self$`versionId`
      }
      if (!is.null(self$`pipelineId`)) {
        TrackingModelObject[['pipelineId']] <- self$`pipelineId`
      }

      TrackingModelObject
    },
    fromJSON = function(TrackingModelJson) {
      TrackingModelObject <- jsonlite::fromJSON(TrackingModelJson)
      if (!is.null(TrackingModelObject$`runId`)) {
        self$`runId` <- TrackingModelObject$`runId`
      }
      if (!is.null(TrackingModelObject$`artifactId`)) {
        self$`artifactId` <- TrackingModelObject$`artifactId`
      }
      if (!is.null(TrackingModelObject$`versionId`)) {
        self$`versionId` <- TrackingModelObject$`versionId`
      }
      if (!is.null(TrackingModelObject$`pipelineId`)) {
        self$`pipelineId` <- TrackingModelObject$`pipelineId`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "runId": %s,
           "artifactId": %s,
           "versionId": %s,
           "pipelineId": %s
        }',
        self$`runId`,
        self$`artifactId`,
        self$`versionId`,
        self$`pipelineId`
      )
    },
    fromJSONString = function(TrackingModelJson) {
      TrackingModelObject <- jsonlite::fromJSON(TrackingModelJson)
      self$`runId` <- TrackingModelObject$`runId`
      self$`artifactId` <- TrackingModelObject$`artifactId`
      self$`versionId` <- TrackingModelObject$`versionId`
      self$`pipelineId` <- TrackingModelObject$`pipelineId`
    }
  )
)
