# Dkube api server
#
# No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
#
# OpenAPI spec version: 2.2.1.11
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' VersionModel Class
#'
#' @field name 
#' @field uuid 
#' @field tags 
#' @field description 
#' @field index 
#' @field timestamps 
#' @field syncState 
#' @field storagePath 
#' @field user 
#' @field datumName 
#' @field datumUUID 
#' @field runUUID 
#' @field trackingUUID 
#' @field commitID 
#' @field datumType 
#' @field model 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VersionModel <- R6::R6Class(
  'VersionModel',
  public = list(
    `name` = NULL,
    `uuid` = NULL,
    `tags` = NULL,
    `description` = NULL,
    `index` = NULL,
    `timestamps` = NULL,
    `syncState` = NULL,
    `storagePath` = NULL,
    `user` = NULL,
    `datumName` = NULL,
    `datumUUID` = NULL,
    `runUUID` = NULL,
    `trackingUUID` = NULL,
    `commitID` = NULL,
    `datumType` = NULL,
    `model` = NULL,
    initialize = function(`name`, `uuid`, `tags`, `description`, `index`, `timestamps`, `syncState`, `storagePath`, `user`, `datumName`, `datumUUID`, `runUUID`, `trackingUUID`, `commitID`, `datumType`, `model`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`uuid`)) {
        stopifnot(is.character(`uuid`), length(`uuid`) == 1)
        self$`uuid` <- `uuid`
      }
      if (!missing(`tags`)) {
        stopifnot(is.list(`tags`), length(`tags`) != 0)
        lapply(`tags`, function(x) stopifnot(is.character(x)))
        self$`tags` <- `tags`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`index`)) {
        stopifnot(is.numeric(`index`), length(`index`) == 1)
        self$`index` <- `index`
      }
      if (!missing(`timestamps`)) {
        stopifnot(R6::is.R6(`timestamps`))
        self$`timestamps` <- `timestamps`
      }
      if (!missing(`syncState`)) {
        stopifnot(is.character(`syncState`), length(`syncState`) == 1)
        self$`syncState` <- `syncState`
      }
      if (!missing(`storagePath`)) {
        stopifnot(is.character(`storagePath`), length(`storagePath`) == 1)
        self$`storagePath` <- `storagePath`
      }
      if (!missing(`user`)) {
        stopifnot(is.character(`user`), length(`user`) == 1)
        self$`user` <- `user`
      }
      if (!missing(`datumName`)) {
        stopifnot(is.character(`datumName`), length(`datumName`) == 1)
        self$`datumName` <- `datumName`
      }
      if (!missing(`datumUUID`)) {
        stopifnot(is.character(`datumUUID`), length(`datumUUID`) == 1)
        self$`datumUUID` <- `datumUUID`
      }
      if (!missing(`runUUID`)) {
        stopifnot(is.character(`runUUID`), length(`runUUID`) == 1)
        self$`runUUID` <- `runUUID`
      }
      if (!missing(`trackingUUID`)) {
        stopifnot(is.character(`trackingUUID`), length(`trackingUUID`) == 1)
        self$`trackingUUID` <- `trackingUUID`
      }
      if (!missing(`commitID`)) {
        stopifnot(is.character(`commitID`), length(`commitID`) == 1)
        self$`commitID` <- `commitID`
      }
      if (!missing(`datumType`)) {
        stopifnot(is.character(`datumType`), length(`datumType`) == 1)
        self$`datumType` <- `datumType`
      }
      if (!missing(`model`)) {
        stopifnot(R6::is.R6(`model`))
        self$`model` <- `model`
      }
    },
    toJSON = function() {
      VersionModelObject <- list()
      if (!is.null(self$`name`)) {
        VersionModelObject[['name']] <- self$`name`
      }
      if (!is.null(self$`uuid`)) {
        VersionModelObject[['uuid']] <- self$`uuid`
      }
      if (!is.null(self$`tags`)) {
        VersionModelObject[['tags']] <- self$`tags`
      }
      if (!is.null(self$`description`)) {
        VersionModelObject[['description']] <- self$`description`
      }
      if (!is.null(self$`index`)) {
        VersionModelObject[['index']] <- self$`index`
      }
      if (!is.null(self$`timestamps`)) {
        VersionModelObject[['timestamps']] <- self$`timestamps`$toJSON()
      }
      if (!is.null(self$`syncState`)) {
        VersionModelObject[['syncState']] <- self$`syncState`
      }
      if (!is.null(self$`storagePath`)) {
        VersionModelObject[['storagePath']] <- self$`storagePath`
      }
      if (!is.null(self$`user`)) {
        VersionModelObject[['user']] <- self$`user`
      }
      if (!is.null(self$`datumName`)) {
        VersionModelObject[['datumName']] <- self$`datumName`
      }
      if (!is.null(self$`datumUUID`)) {
        VersionModelObject[['datumUUID']] <- self$`datumUUID`
      }
      if (!is.null(self$`runUUID`)) {
        VersionModelObject[['runUUID']] <- self$`runUUID`
      }
      if (!is.null(self$`trackingUUID`)) {
        VersionModelObject[['trackingUUID']] <- self$`trackingUUID`
      }
      if (!is.null(self$`commitID`)) {
        VersionModelObject[['commitID']] <- self$`commitID`
      }
      if (!is.null(self$`datumType`)) {
        VersionModelObject[['datumType']] <- self$`datumType`
      }
      if (!is.null(self$`model`)) {
        VersionModelObject[['model']] <- self$`model`$toJSON()
      }

      VersionModelObject
    },
    fromJSON = function(VersionModelJson) {
      VersionModelObject <- jsonlite::fromJSON(VersionModelJson)
      if (!is.null(VersionModelObject$`name`)) {
        self$`name` <- VersionModelObject$`name`
      }
      if (!is.null(VersionModelObject$`uuid`)) {
        self$`uuid` <- VersionModelObject$`uuid`
      }
      if (!is.null(VersionModelObject$`tags`)) {
        self$`tags` <- VersionModelObject$`tags`
      }
      if (!is.null(VersionModelObject$`description`)) {
        self$`description` <- VersionModelObject$`description`
      }
      if (!is.null(VersionModelObject$`index`)) {
        self$`index` <- VersionModelObject$`index`
      }
      if (!is.null(VersionModelObject$`timestamps`)) {
        timestampsObject <- TimeStamps$new()
        timestampsObject$fromJSON(jsonlite::toJSON(VersionModelObject$timestamps, auto_unbox = TRUE))
        self$`timestamps` <- timestampsObject
      }
      if (!is.null(VersionModelObject$`syncState`)) {
        self$`syncState` <- VersionModelObject$`syncState`
      }
      if (!is.null(VersionModelObject$`storagePath`)) {
        self$`storagePath` <- VersionModelObject$`storagePath`
      }
      if (!is.null(VersionModelObject$`user`)) {
        self$`user` <- VersionModelObject$`user`
      }
      if (!is.null(VersionModelObject$`datumName`)) {
        self$`datumName` <- VersionModelObject$`datumName`
      }
      if (!is.null(VersionModelObject$`datumUUID`)) {
        self$`datumUUID` <- VersionModelObject$`datumUUID`
      }
      if (!is.null(VersionModelObject$`runUUID`)) {
        self$`runUUID` <- VersionModelObject$`runUUID`
      }
      if (!is.null(VersionModelObject$`trackingUUID`)) {
        self$`trackingUUID` <- VersionModelObject$`trackingUUID`
      }
      if (!is.null(VersionModelObject$`commitID`)) {
        self$`commitID` <- VersionModelObject$`commitID`
      }
      if (!is.null(VersionModelObject$`datumType`)) {
        self$`datumType` <- VersionModelObject$`datumType`
      }
      if (!is.null(VersionModelObject$`model`)) {
        modelObject <- VersionModelModel$new()
        modelObject$fromJSON(jsonlite::toJSON(VersionModelObject$model, auto_unbox = TRUE))
        self$`model` <- modelObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "uuid": %s,
           "tags": [%s],
           "description": %s,
           "index": %d,
           "timestamps": %s,
           "syncState": %s,
           "storagePath": %s,
           "user": %s,
           "datumName": %s,
           "datumUUID": %s,
           "runUUID": %s,
           "trackingUUID": %s,
           "commitID": %s,
           "datumType": %s,
           "model": %s
        }',
        self$`name`,
        self$`uuid`,
        lapply(self$`tags`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`description`,
        self$`index`,
        self$`timestamps`$toJSON(),
        self$`syncState`,
        self$`storagePath`,
        self$`user`,
        self$`datumName`,
        self$`datumUUID`,
        self$`runUUID`,
        self$`trackingUUID`,
        self$`commitID`,
        self$`datumType`,
        self$`model`$toJSON()
      )
    },
    fromJSONString = function(VersionModelJson) {
      VersionModelObject <- jsonlite::fromJSON(VersionModelJson)
      self$`name` <- VersionModelObject$`name`
      self$`uuid` <- VersionModelObject$`uuid`
      self$`tags` <- VersionModelObject$`tags`
      self$`description` <- VersionModelObject$`description`
      self$`index` <- VersionModelObject$`index`
      TimeStampsObject <- TimeStamps$new()
      self$`timestamps` <- TimeStampsObject$fromJSON(jsonlite::toJSON(VersionModelObject$timestamps, auto_unbox = TRUE))
      self$`syncState` <- VersionModelObject$`syncState`
      self$`storagePath` <- VersionModelObject$`storagePath`
      self$`user` <- VersionModelObject$`user`
      self$`datumName` <- VersionModelObject$`datumName`
      self$`datumUUID` <- VersionModelObject$`datumUUID`
      self$`runUUID` <- VersionModelObject$`runUUID`
      self$`trackingUUID` <- VersionModelObject$`trackingUUID`
      self$`commitID` <- VersionModelObject$`commitID`
      self$`datumType` <- VersionModelObject$`datumType`
      VersionModelModelObject <- VersionModelModel$new()
      self$`model` <- VersionModelModelObject$fromJSON(jsonlite::toJSON(VersionModelObject$model, auto_unbox = TRUE))
    }
  )
)
